jvimalprasathdev/src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Affiliates</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>FullAccess</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Campaign_Score__c</fullName>
        <description>This field stores the Campaign Score contribution for this campaign member record.  If deleted, this value is used to decrement lead score.  If the campaign member is edited, this value will change if rule criteria are now met, or no longer met.</description>
        <inlineHelpText>This field stores the Campaign Score contribution for this campaign member record.  If deleted, this value is used to decrement lead score.  If the campaign member is edited, this value will change if rule criteria are now met, or no longer met.</inlineHelpText>
        <label>Campaign Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

jvimalprasathdev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is to add a  contact to a campaign.</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign_Score__c</fullName>
        <description>Sum of all the lead scoring rules from campaign member lead scoring rules</description>
        <inlineHelpText>Sum of all the lead scoring rules from campaign member lead scoring rules</inlineHelpText>
        <label>Campaign Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Internal_Referral_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referral Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Referral__c</fullName>
        <label>Internal Referral</label>
        <picklist>
            <picklistValues>
                <fullName>MC Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HESC Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSA Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/LeadScoringRule__c.object
<CustomObject>
    <description>This object tracks the lead scoring rules to help prioritize leads based on who they are and what they do.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In-Active rules are NOT evaluated when a lead or campaign member is saved.</description>
        <inlineHelpText>In-Active rules are NOT evaluated when a lead or campaign member is saved.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Selecting a campaign limits the rule to fire only for members of this campaign.  Leaving this blank selects all campaigns.</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Lead Scoring Rules</relationshipLabel>
        <relationshipName>Lead_Scoring_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Label__c</fullName>
        <description>This contains the more readable field label of the Field name.  Note this approach doesn&apos;t solve for an org has two fields with the same label.  There&apos;s a chance the wrong field would be used.</description>
        <label>Field Label</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>Field name used for criteria</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>greater or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>less or equal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>does not contain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Score_Change__c</fullName>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Rule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Lead Scoring Rule</label>
    <nameField>
        <label>LeadScoringRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/testleadscoringbackup.cls
@istest
global class testleadscoringbackup{
 testMethod static void testmethod1(){

         leadscoringbackup lsb =  new leadscoringbackup();
           
         campaign cm = new campaign();
         cm.name='Fake';
         insert cm;
        
         List<Lead> leads = new List<Lead>{};
         List<contact> contacts = new List<contact>{};
         List<campaignmember> cms= new List<campaignmember>{}; 
         Integer i;
                 
        for (i=0;i<5;i++){
            Contact c = new contact(FirstName='John'+i,LastName='Doe'+i);
            contacts.add(c);
        }//for
        insert contacts;
        
        
       user u=[select id from user limit 1];
        for (i=0;i<5;i++){
            Lead l = new Lead(FirstName='John'+i,LastName='Doe'+i,email='test@test.com', Company='test',Property_State__c='DE',Status='New-Not Opened',Applicant_Type__c='Individual',Internal_Referral__c='MC Referral',Channel__c='Centralized Retail',Channel_Sources__c='Bank',Occupancy_Code__c='Owner Occupied',Internal_Referral_Name__c=u.id);
            leads.add(l);
        }//for
        insert leads;
           
         
         for (i=0;i<5;i++)
         {  
         campaignmember cm1 =  new campaignmember();
         cm1.campaignid=cm.id;
         cm1.ContactId=contacts.get(i).id;
         cm1.leadid=leads.get(i).id;
         cm1.Campaign_Score__c = 1;
         cms.add(cm1);
        } 
         insert cms;
         system.debug('%%%%%%%%55'+cms);       
         
         
         LeadScoringRule__c cmscore =  new LeadScoringRule__c(Active__c=true,Campaign__c=cm.id,Field_Label__c='Status',Field_Name__c='Status',Operator__c='equal',Score_Change__c=10,Type__c='Campaign Member',Value__c='Sent');
         insert cmscore;
         LeadScoringRule__c cmscore1 =  new LeadScoringRule__c(Active__c=true,Campaign__c=null,Field_Label__c='Status',Field_Name__c='Status',Operator__c='equal',Score_Change__c=10,Type__c='Lead',Value__c='New-Not Opened');
         insert cmscore1; 
      
      
         LeadScoringBackup.leadScoringClassAlreadyCalled();
        
         set<id> leadids =  new set<id>(); 
         set<id> cmids =  new set<id>(); 
         
         for(lead l:leads)
         {    leadids.add(l.id);   } 
         
         for( campaignmember cam :cms)
         {    cmids.add(cam.id);   } 
           
        
         LeadScoringBackup.evaluateCMs(cmids);
         LeadScoringBackup.evaluateLeads(leadids);
         LeadScoringBackup.deletedCMs(cmids);
         
            
         
         leadscoringbackup.evaluateCriteria('Sent', 'equals', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('Sent', 'equals', 'Sent', schema.DisplayType.BOOLEAN);
         leadscoringbackup.evaluateCriteria('10', 'equals', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'not equal to', 'Sent', schema.DisplayType.BOOLEAN);  
         leadscoringbackup.evaluateCriteria('10', 'not equal to', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'not equal to', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('10', 'greater than', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'greater than', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('10', 'greater or equal', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'greater or equal', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('10', 'less than', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'less than', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('10', 'less or equal', '10', schema.DisplayType.INTEGER);
         leadscoringbackup.evaluateCriteria('Sent', 'less or equal', 'Sent', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('S', 'contains', 'S', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('S', 'starts with', 'S', schema.DisplayType.STRING);
         leadscoringbackup.evaluateCriteria('S', 'does not contain', 'S', schema.DisplayType.STRING);
  }  
   
}