jvimalprasathdev/src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>Campaign_Score__c</fullName>
        <description>This field stores the Campaign Score contribution for this campaign member record.  If deleted, this value is used to decrement lead score.  If the campaign member is edited, this value will change if rule criteria are now met, or no longer met.</description>
        <inlineHelpText>This field stores the Campaign Score contribution for this campaign member record.  If deleted, this value is used to decrement lead score.  If the campaign member is edited, this value will change if rule criteria are now met, or no longer met.</inlineHelpText>
        <label>Campaign Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Campaign_Score__c</fullName>
        <description>Sum of all the lead scoring rules from campaign member lead scoring rules</description>
        <inlineHelpText>Sum of all the lead scoring rules from campaign member lead scoring rules</inlineHelpText>
        <label>Campaign Score</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/LeadScoringRule__c.object
<CustomObject>
    <description>This object tracks the lead scoring rules to help prioritize leads based on who they are and what they do.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>In-Active rules are NOT evaluated when a lead or campaign member is saved.</description>
        <inlineHelpText>In-Active rules are NOT evaluated when a lead or campaign member is saved.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Selecting a campaign limits the rule to fire only for members of this campaign.  Leaving this blank selects all campaigns.</description>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Lead Scoring Rules</relationshipLabel>
        <relationshipName>Lead_Scoring_Rules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Field_Name__c</fullName>
        <description>Field name used for criteria</description>
        <label>Field Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Rule Type</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Campaign Member</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Lead Scoring Rule</label>
    <nameField>
        <label>LeadScoringRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Lead Scoring Rules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/DeleteMe_Test.cls
@isTest
public class DeleteMe_Test{
    /*
    public static testmethod void DeleteMe_method1(){
        DeleteMe.evaluateLeadsAlreadyCalled = false;
        DeleteMe.evaluateLeadsAlreadyCalled();
        DeleteMe.setEvaluateLeadsAlreadyCalled(false);
        DeleteMe.evaluateCMsAlreadyCalled();
        DeleteMe.setEvaluateCMsAlreadyCalled(false);
        list<lead> tl= [select id from lead limit 1];
        list<lead> cms= [select id,Campaign_Score__c from lead limit 1];
        //list<lead> tl = new list<lead>();
        DeleteMe.evaluateLeads(tl, true);
        list<CampaignMember> cs= [select campaign_score__c from CampaignMember limit 1];
        DeleteMe.evaluateCMs(cs);
        Set<Id> ids = (new Map<Id, Lead>([SELECT Id,campaign_score__c FROM Lead])).keySet();
        DeleteMe.updateLeads(ids);
        map<id,double> leadscores = new map<id,double>();
        list<string> fnames = new list<string>();
        list<lead> fna=[select name from lead limit 1];
        for(lead l:fna){
            fnames.add(l.Name);
        }
        for(lead l : cms){
            leadscores.put(l.id,l.Campaign_Score__c);
        }
        //DeleteMe.updateLeads(IDs,leadScores);
        DeleteMe.getRuleFieldNames(fnames);
        campaignmember[] cm=[select id from campaignmember limit 1];
        list<campaignmember> camp=[select id,LeadId, Campaign_Score__c from campaignmember limit 1];
        DeleteMe.updateCMs(cm);
        DeleteMe.deletedCMs(camp);
        DeleteMe.evaluateCriteria(null, 'equals', null, schema.DisplayType.STRING);
    }
    public static testmethod void DeleteMe_method2(){
        DeleteMe.evaluateLeadsAlreadyCalled = true;
        DeleteMe.evaluateLeadsAlreadyCalled();
        DeleteMe.setEvaluateLeadsAlreadyCalled(true);
        DeleteMe.evaluateCMsAlreadyCalled();
        DeleteMe.setEvaluateCMsAlreadyCalled(true);
        list<lead> tl= [select id from lead limit 1];
        list<lead> cms= [select id,Campaign_Score__c from lead limit 1];
        //list<lead> tl = new list<lead>();
        DeleteMe.evaluateLeads(tl, true);
        list<CampaignMember> cs= [select id,campaign_score__c from CampaignMember limit 1];
        LeadScoringRule__c lsco = new LeadScoringRule__c();
        lsco.Active__c = true;
        for(CampaignMember cm:cs)
        {
            lsco.Campaign__c = cm.id;
        }
        lsco.Field_Name__c = 'text';
        lsco.Type__c = 'Campaign Member';
        DeleteMe.activeLeadScoringRuleDetails('Campaign Member');
        DeleteMe.evaluateCMs(cs);
        Set<Id> ids = (new Map<Id, Lead>([SELECT Id,campaign_score__c FROM Lead])).keySet();
        DeleteMe.updateLeads(ids);
        map<id,double> leadscores = new map<id,double>();
        list<string> fnames = new list<string>();
        list<lead> fna=[select name from lead limit 1];
        for(lead l:fna){
            fnames.add(l.Name);
        }
        for(lead l : cms){
            leadscores.put(l.id,l.Campaign_Score__c);
        }
        //DeleteMe.updateLeads(IDs,leadScores);
        DeleteMe.getRuleFieldNames(fnames);
        campaignmember[] cm=[select id from campaignmember limit 1];
        list<campaignmember> camp=[select id,LeadId, Campaign_Score__c from campaignmember limit 1];
        DeleteMe.updateCMs(cm);
        DeleteMe.deletedCMs(camp);
        string equals = 'not equal to';
        DeleteMe.evaluateCriteria(null,equals,'ABC',null);
    }
   */ 
    public static testmethod void DeleteMe_method10(){
        string equals = 'greater than';
        DeleteMe.evaluateCriteria(null,equals, 'ABC', null);
    }
    public static testmethod void DeleteMe_method3(){
        string equals = 'less than';
        DeleteMe.evaluateCriteria(null,equals, 'ABC', null);
    }
    public static testmethod void DeleteMe_method4(){
        string equals = 'greater or equal';
        DeleteMe.evaluateCriteria(null,equals, 'ABC', null);
    }
    public static testmethod void DeleteMe_method5(){
        string equals = 'less or equal';
        DeleteMe.evaluateCriteria(null,equals, null, null);
    }
    public static testmethod void DeleteMe_method6(){
        string equals = 'contains';
        DeleteMe.evaluateCriteria(null,equals, null, null);
    }
    public static testmethod void DeleteMe_method7(){
        string equals = 'does not contain';
        DeleteMe.evaluateCriteria(null,equals, null, null);
    }
    public static testmethod void DeleteMe_method8(){
        string equals = 'starts with';
        DeleteMe.evaluateCriteria(null,equals, null, null);
    }
}