jvimalprasathdev/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <description>This is the type the contact. The contact could be anyone like builder, realtor, attorney, appraiser etc.</description>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>RB</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builder</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the contact.</description>
        <label>Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Apt__c</fullName>
        <label>Borrowers Apt #</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Loan Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <description>This is used to capture the time zone of the customer</description>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Realtor_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <label>Notes</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Realtor Contacts</label>
    <nameField>
        <label>Realtor Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtor Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_RealtorManagement_TestClass.cls
@isTest
Public Class CO_RealtorManagement_TestClass{
    Static testmethod void RealtorContactTRG_testmethod(){
        Lead new_ld = new Lead();
        new_ld.Status='Active';
        new_ld.firstname='AK';
        new_ld.Lastname='Rathore';
        new_ld.Applicant_Type__c='Married Couple';
        new_ld.Channel__c='Home Equity';
        new_ld.Channel_Sources__c='Third Parties';
        new_ld.Channel_Values__c='Realtors';
        new_ld.Borrowers_Country__c='Hong Kong';
        new_ld.Borrowers_City__c='Netherlands';
        new_ld.Borrowers_Address_1__c='A-12 Lonley Road';
        new_ld.Time_Zone__c='CST';
        new_ld.Borrowers_Current_Residence__c='Own';
        new_ld.Company='XXXXXX';
        new_ld.Loan_Approved__c=True;
        new_ld.Borrowers_Zip_Postal_Code__c='32418';
        new_ld.Borrowers_Home_Phone__c='(033) 246-3970';
        new_ld.Occupancy_Code__c='Second Home';
        new_ld.Notes__c='Tomorrow is Saturday ok?';
        new_ld.Property_State__c='CA';
        new_ld.Email='akq@gmail.com';
        new_ld.Phone='(033) 246-3970';
        new_ld.Borrowers_Apt__c='Testa';
        insert new_ld; 
        
        Contact con = new Contact();
        con.LastName='Kumar';
        con.Email='Ak@yahoo.com';
        con.contact_type__c='Realtor';
        con.mailingpostalcode='33333';
        
        insert con; 
        
        List<Contact_Management__c> listcon = new List<Contact_Management__c>();
        Contact_Management__c conm= new Contact_Management__c(Contact__c=con.id,Lead__c=new_ld.id);
        listcon.add(conm);
        insert listcon;
        
        Contact con1 = new Contact(id=con.id);
        con1.contact_type__c='Realtor';
        con1.mailingpostalcode='33333';
        update con1;
        
        Contact con2 = new Contact();
        con2.LastName='Sas';
        con2.contact_type__c='RB';
        con2.mailingpostalcode='33333';
        insert con2;
        
        List<Contact_Management__c> listcon1 = new List<Contact_Management__c>();
        Contact_Management__c conm1= new Contact_Management__c(Contact__c=con2.id,Lead__c=new_ld.id);
        listcon1.add(conm1);
        insert listcon1;
        
        Realtor_contacts__c rc= new Realtor_contacts__c();
        rc.name='Lee';
        rc.mailing_zip_postal_code__c='44444';
        rc.contact__c=con2.id;
        insert rc;
        
        Contact con3 = new Contact(id=con2.id);
        con3.email='lee@lee.com';
        con3.contact_type__c='Realtor';
        update con3;
        
        Contact con4 = new Contact(id=con2.id);
        con4.Contact_type__c='New';
        update con4;    
        
       /* lead l1 = [select id from lead limit 1];
        id leadid = l1.id;
        Contact_Management__c test;
       // test.contact__c=con3.id;
        test.lead__c=leadid;
        insert test;*/
        
                  
    }
    Static testmethod void RealtorContactMgmt_testmethod(){
        Lead new_ld = new Lead();
        new_ld.Status='Active';
        new_ld.firstname='AK';
        new_ld.Lastname='Rathore';
        new_ld.Applicant_Type__c='Married Couple';
        new_ld.Channel__c='Home Equity';
        new_ld.Channel_Sources__c='Third Parties';
        new_ld.Channel_Values__c='Realtors';
        new_ld.Borrowers_Country__c='Hong Kong';
        new_ld.Borrowers_City__c='Netherlands';
        new_ld.Borrowers_Address_1__c='A-12 Lonley Road';
        new_ld.Time_Zone__c='CST';
        new_ld.Borrowers_Current_Residence__c='Own';
        new_ld.Company='XXXXXX';
        new_ld.Loan_Approved__c=True;
        new_ld.Borrowers_Zip_Postal_Code__c='32418';
        new_ld.Borrowers_Home_Phone__c='(033) 246-3970';
        new_ld.Occupancy_Code__c='Second Home';
        new_ld.Notes__c='Tomorrow is Saturday ok?';
        new_ld.Property_State__c='CA';
        new_ld.Email='akq@gmail.com';
        new_ld.Phone='(033) 246-3970';
        new_ld.Borrowers_Apt__c='Testa';
        insert new_ld;
        
        Realtor_contacts__c rc= new Realtor_contacts__c();
        rc.name='Lee';
        rc.mailing_zip_postal_code__c='44444';
        insert rc;
        
        List<Realtor_Contact_Management__c> listcon = new List<Realtor_Contact_Management__c>();
        Realtor_Contact_Management__c conm= new Realtor_Contact_Management__c(Realtor_Contact__c=rc.id,Lead__c=new_ld.id);
        listcon.add(conm);
        insert listcon;
        
        system.currentPageReference().getParameters().put('id',new_ld.id);
        ApexPages.StandardSetController sc = new ApexPages.standardSetController(listcon);
        CO_RealtorManagement_CL cntrl= new CO_RealtorManagement_CL(sc);
        cntrl.SaveRelMgt();
        cntrl.Cancel();
        cntrl.RelMgt.Realtor_Contact__c=rc.id;
        cntrl.SaveRelMgt();
        cntrl.RelMgt.Realtor_Contact__c=new_ld.id;
        cntrl.SaveRelMgt();
        
        delete listcon;
    }
    Static testmethod void RealtorContactSearch_testmethod(){
        Realtor_contacts__c rc= new Realtor_contacts__c();
        rc.name='Lee';
        rc.mailing_zip_postal_code__c='44444';
        insert rc;
        
        CO_SearchRealtorContacts_CL SRC= new CO_SearchRealtorContacts_CL();
        src.zipcode='44444';
        src.findRealtorCons();
        src.getVFContacts();
        src.zipcode='44443';
        src.findRealtorCons();
    }
}