jvimalprasathdev/src/objects/Contact_Management__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.InActive__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Managements</relationshipLabel>
        <relationshipName>Contact_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contact Managements</relationshipLabel>
        <relationshipName>Contact_Managements</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Contact Management</label>
    <nameField>
        <displayFormat>CM-{000000}</displayFormat>
        <label>Contact Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contact Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_ContactManagement_CL.cls
/*
Name: CO_ContactManagement_CL
Author: Leena N
Description: This Class is used to create a new Contact(Contact Management) to Lead
Last modified by: Leena N
*/
public class CO_ContactManagement_CL{
    public Contact_Management__c ConMgt{set; get;}
    public id LeadId{get; set;}
    
    public CO_ContactManagement_CL(ApexPages.StandardSetController controller){
        LeadId= system.currentPageReference().getParameters().get('id');        
        ConMgt= new Contact_Management__c();
        ConMgt.Lead__c = Leadid;
    }
    //Method to save the new Contact management record
    public PageReference SaveConMgt(){
        try{
        if(ConMgt.Contact__c!=null){
            insert ConMgt;
         PageReference pr = new PageReference('/' + LeadId);  
         pr.setRedirect(true);  
         return pr;
         }
         else{
              ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL,'Enter Contact')); 
              return null;
         }
         }
         catch(Exception e){
         }
         return null;
    }
    //Method to return to lead page
    public PageReference Cancel(){
        return (new pageReference('/' +LeadId));
    }
}