jvimalprasathdev/src/objects/Customer_Portal_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrower_State_2__c</fullName>
        <label>Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is to specify borrower’s county.</inlineHelpText>
        <label>Borrowers_Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_County__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is to specify borrower’s county.</inlineHelpText>
        <label>Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_date__c</fullName>
        <label>Closing date</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Create_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DU_Response__c</fullName>
        <label>DU Response</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved/Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Daytime_Phone__c</fullName>
        <label>Daytime Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Status__c</fullName>
        <label>Lead Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Interest__c</fullName>
        <label>Loan Interest</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <label>Loan Status</label>
        <picklist>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_number__c</fullName>
        <label>Loan number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mortgage_Consultant_Name__c</fullName>
        <label>Mortgage Consultant Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>180</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>Borrowers_Address_1__c +&apos;,&apos;+ Borrowers_Address_2__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RB_Branch__c</fullName>
        <label>RB Branch</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <label>Submitted</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <label>Suffix</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>RB Portal</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Customer Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_County__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closing_Date__c</fullName>
        <label>Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DU_Response__c</fullName>
        <label>DU Response</label>
        <picklist>
            <picklistValues>
                <fullName>Approved/Eligible</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Interest__c</fullName>
        <label>Loan Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Loan_Number__c</fullName>
        <label>Loan Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <label>Loan Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Term__c</fullName>
        <label>Loan Term</label>
        <picklist>
            <picklistValues>
                <fullName>15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Mortgage_Consultant_Name__c</fullName>
        <label>Mortgage Consultant Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RB_Branch__c</fullName>
        <label>RB Branch</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submitted__c</fullName>
        <label>Submitted</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Suffix__c</fullName>
        <description>This is to specify the borrower’s suffix</description>
        <label>Suffix</label>
        <picklist>
            <picklistValues>
                <fullName>Jr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>II</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>III</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IV</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VI</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_CustomerPortalController.cls
public class CO_CustomerPortalController {

   
    //For creating Customer portal Lead.
    Public Customer_Portal_Lead__c CPLead {set;get;}
    //for lead detail page
    Public Customer_Portal_Lead__c CPLead2 {set;get;}
    Id CpLeadid;
    Public Boolean Lead_check {get;set;}
    
    
    Public String paramSelectedBr;
    Public String paramSelectedDist;
    public string SelectedRegion {get;set;}
    public string SelectedBranch {get;set;}
    public string SelectedDistrict {get;set; }
    public List<selectOption> branchoption {get;set;}
    public list<SelectOption> districtoption{get;set;}
    public Decimal BranchCostCenter {get;set;}
    public String BranchNumber {get;set;}
    public string RB_EID {get;set;}
   
  
    Public String createdlead_firstName {get;set;}
    Public String createdlead_lastName {get;set;}
   

    
    public CO_CustomerPortalController(ApexPages.StandardController controller){
      
        paramSelectedBr= System.currentPagereference().getParameters().get('branch');
        paramSelectedDist= System.currentPagereference().getParameters().get('district');
       
        CPLead = new Customer_Portal_Lead__c(); 
      
        CPLeadid = ApexPages.currentPage().getParameters().get('id');  
        
        if(CPLeadid!=null) {
        CPLead2 = [Select ownerId,Comments__c,Loan_Interest__c,Loan_Term__c,Closing_date__c,Lead_Status__c,Create_Lead__c,Applicant_Type__c,Borrowers_Country__c,Borrowers_Address_1__c,Borrowers_Address_2__c,Borrowers_City__c,Borrowers_County__c,Borrowers_Home_Phone__c,Borrower_State_2__c,Borrowers_Zip_Postal_Code__c,Daytime_Phone__c,DU_Response__c,Email__c,First_Name__c,Last_Name__c,Loan_Status__c,Name__c,Occupancy_Code__c,Property_State__c,Suffix__c,Submitted__c,Loan_Number__c,Mortgage_Consultant_Name__c,Property_Address__c,RB_Branch__c,RB_District__c,RB_Region__c,RB_Cost_Center__c,RelationShip_Banker_EID__c,Closing_Fees__c,Branch_ID__c,Application_number__c,Empower_Lead_ID__c,Transfer_to_HLR__c  from Customer_Portal_Lead__c where id=:CPLEadid limit 500]; 
        // Added for B-142315 (12B).
        createdlead_firstName = CPLead2.First_Name__c;
        createdlead_lastName = CPLead2.Last_Name__c;    
        }
        
    }
    
 
    public PageReference submit() {
    
        system.debug('*******CPlead'+CPLead);
        Lead_check = false;
        boolean InsertL;
        string zipcode = CPLead.Borrowers_Zip_Postal_Code__c; 
        try{

            if(CPLead.First_Name__c == null || CPLead.Last_Name__c == null ||CPLead.Borrowers_Home_Phone__c == null  || CPLead.Daytime_Phone__c == null ||
            CPLead.Marrital_Status__c == null || CPLead.Applicant_Type__c == null || CPLead.Borrowers_Address_1__c == null || CPLead.Borrower_State_2__c == null ||
            CPLead.Borrowers_Zip_Postal_Code__c == null || CPLead.Preferred_Contact_Method__c == null || CPLead.Time_Zone__c == null || CPLead.Best_Contact_Time__c == null
            || CPLead.How_did_you_hear_about_us__c == null || CPLead.Loan_Purpose__c == null || CPLead.Total_amount_finance_needed__c == null || CPLead.Property_State__c == null
            || CPLead.Property_Use__c == null || CPLead.Property_Type__c == null) {
            
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Enter the details in Mandatory fields(*)'));
                InsertL = false;
            }
            
            if (CPLead.Property_State__c != 'TX' && CPLead.Property_State__c != 'MD' && CPLead.Property_State__c != 'LA'
            && CPLead.Property_State__c != 'DE' && CPLead.Property_State__c != 'NY' && CPLead.Property_State__c != 'NJ'
            && CPLead.Property_State__c != 'CT' && CPLead.Property_State__c != 'VA' && CPLead.Property_State__c != 'DC') {
            system.debug('%%%%%%%%%%%CPLead.Property_State__c%%%%%%%%'+CPLead.Property_State__c);
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter a correct state'));
                InsertL = false;
                //system.debug('########################test 1####################'+InsertL );
            }
            else if(zipcode.Length() != 5) {
                ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Please enter a correct Zip code'));
                InsertL = false;
            }
            else{
                CPLead.Create_Lead__c = true;
                
                 CPLead.RB_Branch__c = paramSelectedBr;
                 CPLead.RB_District__c = paramSelectedDist;
                 CPLead.RB_Region__c = SelectedRegion;
                 CPLead.RelationShip_Banker_EID__c = RB_EID;
                 Branch__c bcc = [Select Cost_Center__c,Branch_Number__c From Branch__c where Name = :paramSelectedBr];
                 BranchCostCenter = bcc.Cost_Center__c; 
                 BranchNumber = bcc.Branch_Number__c;
                 CPLead.RB_Cost_Center__c = String.ValueOf(BranchCostCenter) ;
                 //CPLead.Branch_ID__c = BranchNumber; 
 

               //system.debug('**paramSelectedBr ***'+paramSelectedBr);
               //system.debug('**paramSelectedDist ***'+paramSelectedDist); 
               //system.debug('**paramSelectedCostCenter***'+paramSelectedCostCenter);
               //system.debug('*****SelectedRegion*****'+SelectedRegion);
               //system.debug('*****RB_EID*****'+RB_EID);
               
               
                InsertL = true;
            }
                system.debug('########################test 2#####################'+InsertL );     
            if(InsertL == true){
              //system.debug('########################insrerting#####################');
              //   CPLead.District__c = string.valueOf(districtoption[0].getvalue());
                insert CPLead ;
                InsertL = false;   
                PageReference pageRef= new PageReference('/apex/CO_successfullysubmitted_VF?id='+CPLead.id);
                 pageRef.getParameters().put('branch',paramSelectedBr);
                 pageRef.getParameters().put('district',paramSelectedDist);
                pageRef.setredirect(true);        
                return pageRef;       
            }
            return null; 
    }catch (exception e) {
         CPLead.Create_Lead__c = false;
         ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Please check the values entered'));
         System.debug('*******Following error occured'+e);
         return null;
    }
    }
    
    public void onload() {
    
    CPLead.Borrowers_Home_Phone__c = '()-';
    CPLead.Daytime_phone__c = '()-';
    CPLead.Sales_price__c = 0.00;
    CPLead.Approximate_value_of_your_property__c = 0.00;
    
    }
    
    
    public PageReference Close(){
        
               system.debug('**paramSelectedBr ***'+paramSelectedBr);
               system.debug('**paramSelectedDist ***'+paramSelectedDist); 
              // system.debug('**paramSelectedCostCenter***'+paramSelectedCostCenter);
        PageReference pageRef= new PageReference('/apex/RB_Portal_List_View');          
        pageRef.getParameters().put('branch',paramSelectedBr);
        pageRef.getParameters().put('district',paramSelectedDist);
      //  pageRef.getParameters().put('costCenter',paramSelectedCostCenter);
        pageRef.setredirect(true);        
        return pageRef;
    }  
    
    public PageReference Previous(){
        
        PageReference pageRef= new PageReference('/apex/CO_CustomerAssessment_VF');
        pageRef.getParameters().put('branch',paramSelectedBr);
        pageRef.getParameters().put('district',paramSelectedDist);
      //  pageRef.getParameters().put('costCenter',paramSelectedCostCenter);
        pageRef.setredirect(true);        
        return pageRef;
    }
  
   }