jvimalprasathdev/src/objects/Customer_Portal_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>property_located__c</fullName>
        <label>Where is the property located?</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <label>RB Portal</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Customer Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_PortalLeadDetailController_Test.cls
@istest
public class CO_PortalLeadDetailController_Test{ 
 Static Testmethod Void TestCO_PortalLeadDetailController(){ 
 
 Customer_Portal_Lead__c CPLead = new Customer_Portal_Lead__c();
 CPLead.property_located__c = 'TX';
 CPLead.property_state__c = 'TX';
 insert cplead;
 PageReference pageRef = page.CO_PortalLeadDetail_VF;
 Test.setCurrentPage(pageRef);
 pageRef.getParameters().put('id',CPlead.id);
 ApexPages.StandardController sc = new ApexPages.standardController(cplead);
 
 CO_PortalLeadDetailController pld = new CO_PortalLeadDetailController(sc);
 pld.SaveNote();
 pld.ClosePopUp();
 pld.CreateLead();
 pld.showsubmit();
 pld.backbutton ();
 }
 }