jvimalprasathdev/src/objects/Customer_Portal_Lead__c.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Create_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Lead</label>
        <type>Checkbox</type>
    </fields>
    <label>RB Portal</label>
    <nameField>
        <displayFormat>CP-{0000000000}</displayFormat>
        <label>Customer Lead  Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Customer Portal Leads</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_PortalLeadDetailController.cls
public with sharing class CO_PortalLeadDetailController{

     Public Customer_Portal_Lead__c CPLead2 {set;get;}
     Id CpLeadid;
     Public Boolean displayPopUp {get;set;} 
     Public Boolean showsubmitbtn{get;set;} 
     public CO_PortalLeadDetailController(ApexPages.StandardController controller){
        CPLead2 = new Customer_Portal_Lead__c(); 
        CPLeadid = ApexPages.currentPage().getParameters().get('id');   
        if(CPLeadid!=null)
            CPLead2 = [Select Comments__c,Create_Lead__c from Customer_Portal_Lead__c where id=:CPLEadid];        
     
     system.debug('++++++CPLead2.Create_Lead__c++++'+CPLead2.Create_Lead__c);
     }
     
     public void SaveNote(){
         if(CPLead2!=null)
             update CPLead2 ; 
     }
     
     Public void ClosePopUp(){
         displayPopUp = false;    
     }
     Public pagereference CreateLead(){ 
         
         if(CPLead2.Create_Lead__c != true){
             displayPopUp = true;
             CPLead2.Create_Lead__c = true;
             Update CPLead2; 
             }               
     pagereference pageref = new pagereference('/apex/CO_RBPipeline_VF');
            // pageref.setredirect(true);
             return pageref;

     }
     public void showsubmit() {
     if (CPLead2.Create_Lead__c == false) {
     showsubmitbtn = true;
     }
     }
     public pagereference backbutton () {
     pagereference pageref = new pagereference('/apex/CO_RBPipeline_VF');
     return pageref;
     }
}