jvimalprasathdev/src/objects/ErrorLogDetail__c.object
<CustomObject>
    <description>Captures Error - Used to log Technical/ Business Exceptions.</description>
    <fields>
        <fullName>Error_Message__c</fullName>
        <description>The Entire Error Message.</description>
        <label>Error Message</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Error_Source__c</fullName>
        <label>Error Source</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Type__c</fullName>
        <description>Type of Exception</description>
        <label>Error Type</label>
        <picklist>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OPUS Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Record_ID__c</fullName>
        <description>Holds Error record ID</description>
        <label>Error Record ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Severity__c</fullName>
        <label>Severity</label>
        <picklist>
            <picklistValues>
                <fullName>Critical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Error Log Detail</label>
    <nameField>
        <displayFormat>ERRLOG-{00000}</displayFormat>
        <label>ErrorLogDetail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Log Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/ErrorLogCleanUpTest.cls
@istest
public with sharing class ErrorLogCleanUpTest {
	
	static testMethod void ErrorLogCleanTest(){
		
		
		Test.startTest();
	/*	List<Profile> pList=[Select Id FROM Profile WHERE Name = 'SOFI API' ];
		Id pID=null;
		for(Profile p:pList)
		{
			pID=p.Id;
		}
		User uRec=[Select Id FROM User WHERE ProfileId=:pID AND IsActive = true limit 1];
		//List<User> uList=[Select Id FROM User WHERE ProfileId=:pID limit 1];
		//Id uID=null;
		//for(User u:uList)
		//{
			//uID=u.Id;
		//}*/
		 User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];//Added by vimal for the story B-653680
		System.runAs(thisUser)
		{
			Date currentDate=Date.newInstance(Date.Today().year(), Date.Today().month(), Date.Today().day());
			ErrorLogDetail__c errLog=new ErrorLogDetail__c();
			errLog.Record_ID__c='12345';
			errLog.Error_Type__c='Technical';
			errLog.Error_Source__c='API';
			errLog.Error_Message__c='Error Log created by the test class';
			errLog.Severity__c='Low';
			insert errLog;
			
			ErrorLogCleanUp sh1 = new ErrorLogCleanUp();
			String sch = '0 0 23 * * ?'; 
			system.schedule('Test Error Logs', sch, sh1); 
			
		}
		Test.stopTest();	
	}

}