jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BorrowersHouse__c</fullName>
        <label>Borrowers House#</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Apt__c</fullName>
        <label>Borrowers Apt #</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_County__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_State__c</fullName>
        <description>This is to specify borrower’s State.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of co-borrower’s address.</description>
        <label>Co-Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of co-borrower’s address.</description>
        <label>Co-Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Apt__c</fullName>
        <label>Co-Borrowers Apt #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_City__c</fullName>
        <description>This is to specify co-borrower’s city</description>
        <label>Co-Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Country__c</fullName>
        <description>This is to specify co-borrower’s country.</description>
        <label>Co-Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_County__c</fullName>
        <description>This is to specify co-borrower’s county</description>
        <label>Co-Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Home_Phone__c</fullName>
        <description>This is to specify co-borrower’s home phone.</description>
        <label>Co-Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_House__c</fullName>
        <label>Co-Borrowers House#</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_State__c</fullName>
        <description>This is to specify co-borrower’s State.</description>
        <label>Co-Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify co-borrower’s zip.</description>
        <label>Co-Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_Borrower_Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrower Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copy_Borrowers_Home_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrowers Home Phone</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/UpdateLeadDetails.cls
public class UpdateLeadDetails{
    public void updateAddressAndPhone(List<Lead> Lead_Details){
        for (Lead l : Lead_Details){
           if(l.Copy_Borrower_Current_Address__c == true){     
             if(l.Co_Borrowers_Address_1__c!=null || l.Co_Borrowers_Address_2__c!=null ||
                l.Co_Borrowers_City__c != null ||  l.Co_Borrowers_House__c != null || 
                l.Co_Borrowers_Country__c != null ||l.Co_Borrowers_County__c != null ||
                l.Co_Borrowers_State__c != null ||l.Co_Borrowers_Zip_Postal_Code__c != null|| l.Co_Borrowers_Apt__c != null){
                      if(l.Co_Borrowers_Address_1__c != l.Borrowers_Address_1__c ||l.Co_Borrowers_Address_2__c != l.Borrowers_Address_2__c||
                         l.Co_Borrowers_City__c != l.Borrowers_City__c ||l.Co_Borrowers_House__c != l.BorrowersHouse__c ||
                         l.Co_Borrowers_Country__c != l.Borrowers_Country__c || l.Co_Borrowers_County__c != l.Borrowers_County__c ||
                         l.Co_Borrowers_State__c != l.Borrowers_State__c || l.Co_Borrowers_Zip_Postal_Code__c != l.Borrowers_Zip_Postal_Code__c ||
                         l.Co_Borrowers_Apt__c!= l.Borrowers_Apt__c){
                                 l.Copy_Borrower_Current_Address__c = false;
                       }
             }else{
                   l.Co_Borrowers_Address_1__c = l.Borrowers_Address_1__c;    
                   l.Co_Borrowers_Address_2__c = l.Borrowers_Address_2__c;  
                   l.Co_Borrowers_House__c = l.BorrowersHouse__c;  
                   l.Co_Borrowers_Zip_Postal_Code__c = l.Borrowers_Zip_Postal_Code__c;  
                   l.Co_Borrowers_City__c = l.Borrowers_City__c;  
                   l.Co_Borrowers_State__c = l.Borrowers_State__c;  
                   l.Co_Borrowers_County__c = l.Borrowers_County__c;  
                   l.Co_Borrowers_Country__c = l.Borrowers_Country__c;     
                   l.Co_Borrowers_Apt__c = l.Borrowers_Apt__c;  
             }  
             l.Copy_Borrower_Current_Address__c = false;                  
           }  
           if(l.Copy_Borrowers_Home_Phone__c == true){    
           	// Updated for B-3472849   --- Start  
           		   l.Co_Borrowers_Home_Phone__c = l.Borrowers_Home_Phone__c;
                   l.Copy_Borrowers_Home_Phone__c = false;
           	/*  
           	 
              if (l.Co_Borrowers_Home_Phone__c!=null){
                   //if(l.Co_Borrowers_Home_Phone__c!=l.Borrowers_Home_Phone__c){
                      //l.Copy_Borrowers_Home_Phone__c = false;
                   //}
                   // Flag is cleared irrespective of the check on the Home phone field.
                   l.Copy_Borrowers_Home_Phone__c = false;
               }else{
                  if (l.Co_Borrowers_Home_Phone__c == null){
                     l.Co_Borrowers_Home_Phone__c = l.Borrowers_Home_Phone__c;
                     l.Copy_Borrowers_Home_Phone__c = false;
                  }        
               }
            */
            // Updated for B-3472849   --- End
           }  
        }   
    }
}