jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>DNC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is used to specify if the customer does not want to be called.</description>
        <inlineHelpText>Check it if Customer does not wish to be called</inlineHelpText>
        <label>Do not call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Internal_Referral_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Internal Referral Name</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Referral__c</fullName>
        <label>Internal Referral</label>
        <picklist>
            <picklistValues>
                <fullName>MC Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HESC Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CSA Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
                <default>true</default>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/testleadupdate.cls
@istest
global class testleadupdate{
 testMethod static void testmethod1(){
       integer i;
       list<lead> leads=new list<lead>();
       user u=[select id from user limit 1];
        for (i=0;i<2;i++){
            Lead l = new Lead(FirstName='John'+i,LastName='Doe'+i, email='test@test.com',Company='test',Property_State__c='DE',Status='New-Not Opened',Applicant_Type__c='Individual',Internal_Referral__c='MC Referral',Channel__c='Centralized Retail',Channel_Sources__c='Bank',Occupancy_Code__c='Owner Occupied',Internal_Referral_Name__c=u.id);
            leads.add(l);
        }//for
       
         insert leads;
         
         Test.StartTest();
         LeadUpdate leadupdates =  new LeadUpdate();
         leadupdates.query='SELECT  firstname,lastname,DoNotCall,  DNC__c  FROM Lead where Internal_Referral_Name__c=u.id ';
         ID batchprocessid = Database.executeBatch(leadupdates);
         Test.StopTest();
        
       
       }
       
       
 }