jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Email__c</fullName>
        <description>This is to specify co-borrower’s email address.</description>
        <label>Co-Borrowers Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_First_Name__c</fullName>
        <description>This is to specify the co-borrower’s first name.</description>
        <label>Co-Borrowers First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Last_Name__c</fullName>
        <description>This is to specify the co-borrower’s last name.</description>
        <label>Co-Borrowers Last Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <description>This is to specify the loan type of the lead.</description>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Amount__c</fullName>
        <description>This is to specify the requested loan amount in dollars.</description>
        <label>Requested Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <recordTypes>
        <fullName>Prequal</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>Standard Record Type for users creating leads and for leads that haven&apos;t been converted</description>
        <label>Prequal</label>
    </recordTypes>
    <recordTypes>
        <fullName>Web</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <label>Web</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadConversionDuplicates_Test.cls
@istest
public class LeadConversionDuplicates_Test{

public static testmethod void test_LeadConversionDuplicates(){

        id i=[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;

        Lead TestLead = new Lead();    
        TestLead.channel__c = 'Centralized Retail';  
        TestLead.Channel_Sources__c = 'web';
        TestLead.Channel_Values__c = 'Google';
        TestLead.FirstName = 'ABCD';
        TestLead.LastName = 'ABCD';
        TestLead.Email = 'test@test.com';
       // TestLead.Co_Borrowers_First_Name__c = 'xyz';
       // TestLead.Co_Borrowers_Last_Name__c = 'xyz';
       // TestLead.Co_Borrowers_Email__c = 'xyz@xyz.com';
        TestLead.Applicant_Type__c = 'Individual';
        TestLead.Borrowers_Current_Residence__c = 'own';
        TestLead.Property_State__c = 'TX';
        TestLead.Loan_Type__c = 'HE';
        TestLead.Occupancy_Code__c = 'Owner Occupied';
        TestLead.Requested_Loan_Amount__c = 12345;
        TestLead.Loan_Purpose__c = 'Purchase';
        TestLead.Status = 'New - Not Opened';
        TestLead.Property_State__c = 'TX';   
        TestLead.Company = 'ABCD';
        TestLead.RecordTypeId = i;//[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead;
        
        Lead TestLead1 = new Lead();    
        TestLead1.channel__c = 'Centralized Retail';  
        TestLead1.Channel_Sources__c = 'web';
        TestLead1.Channel_Values__c = 'Google';
        TestLead1.FirstName = 'ABCD';
        TestLead1.LastName = 'ABCD';
        TestLead1.Email = 'test@test.com';
        TestLead1.Applicant_Type__c = 'Individual';
        TestLead1.Borrowers_Current_Residence__c = 'own';
        TestLead1.Property_State__c = 'TX';
        TestLead1.Loan_Type__c = 'HE';
        TestLead1.Occupancy_Code__c = 'Owner Occupied';
        TestLead1.Requested_Loan_Amount__c = 12345;
        TestLead1.Loan_Purpose__c = 'Purchase';
        TestLead1.Status = 'New - Not Opened';
        TestLead1.Property_State__c = 'TX';   
        TestLead1.Company = 'ABCD';
        TestLead1.RecordTypeId = i;//[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead1;
        
        
        Lead TestLead2 = new Lead();    
        TestLead2.channel__c = 'Centralized Retail';  
        TestLead2.Channel_Sources__c = 'web';
        TestLead2.Channel_Values__c = 'Google';
        TestLead2.FirstName = 'ABCD';
        TestLead2.LastName = 'ABCD';
        TestLead2.Email = 'test@test.com';
        TestLead2.Co_Borrowers_First_Name__c = 'xyz';
        TestLead2.Co_Borrowers_Last_Name__c = 'xyz';
        TestLead2.Co_Borrowers_Email__c = 'xyz@xyz.com';
        TestLead2.Applicant_Type__c = 'Individual';
        TestLead2.Borrowers_Current_Residence__c = 'own';
        TestLead2.Property_State__c = 'TX';
        TestLead2.Loan_Type__c = 'HE';
        TestLead2.Occupancy_Code__c = 'Owner Occupied';
        TestLead2.Requested_Loan_Amount__c = 12345;
        TestLead2.Loan_Purpose__c = 'Purchase';
        TestLead2.Status = 'New - Not Opened';
        TestLead2.Property_State__c = 'TX';   
        TestLead2.Company = 'ABCD';
        TestLead2.RecordTypeId = i;//[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead2;
        
        
        Lead TestLead3 = new Lead();    
        TestLead3.channel__c = 'Centralized Retail';  
        TestLead3.Channel_Sources__c = 'web';
        TestLead3.Channel_Values__c = 'Google';
        TestLead3.FirstName = 'ABCDABCD';
        TestLead3.LastName = 'ABCDABCD';
        TestLead3.Email = 'test@test.com';
        TestLead3.Co_Borrowers_First_Name__c = 'xyz';
        TestLead3.Co_Borrowers_Last_Name__c = 'xyz';
        TestLead3.Co_Borrowers_Email__c = 'xyz@xyz.com';
        TestLead3.Applicant_Type__c = 'Individual';
        TestLead3.Borrowers_Current_Residence__c = 'own';
        TestLead3.Property_State__c = 'TX';
        TestLead3.Loan_Type__c = 'HE';
        TestLead3.Occupancy_Code__c = 'Owner Occupied';
        TestLead3.Requested_Loan_Amount__c = 12345;
        TestLead3.Loan_Purpose__c = 'Purchase';
        TestLead3.Status = 'New - Not Opened';
        TestLead3.Property_State__c = 'TX';   
        TestLead3.Company = 'ABCD';
        TestLead3.RecordTypeId = i;//[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead3;
        /*
        Lead TestLead4 = new Lead();    
        TestLead4.channel__c = 'Centralized Retail';  
        TestLead4.Channel_Sources__c = 'web';
        TestLead4.Channel_Values__c = 'Google';
        TestLead4.FirstName = 'ABCDABCD';
        TestLead4.LastName = 'ABCDABCD';
        TestLead4.Email = 'test@test.com';
        TestLead4.Co_Borrowers_First_Name__c = 'xyz';
        TestLead4.Co_Borrowers_Last_Name__c = 'xyz';
        TestLead4.Co_Borrowers_Email__c = 'xyz@xyz.com';
        TestLead4.Applicant_Type__c = 'Individual';
        TestLead4.Borrowers_Current_Residence__c = 'own';
        TestLead4.Property_State__c = 'TX';
        TestLead4.Loan_Type__c = 'HE';
        TestLead4.Occupancy_Code__c = 'Owner Occupied';
        TestLead4.Requested_Loan_Amount__c = 12345;
        TestLead4.Loan_Purpose__c = 'Purchase';
        TestLead4.Status = 'New - Not Opened';
        TestLead4.Property_State__c = 'TX';   
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = i;//[select Id from RecordType where Name Like: 'Prequal' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        */
}
}