jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Borrowers_Mobile_Phone__c</fullName>
        <description>This is to specify borrower’s mobile phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower. In this phase, this lead number will be entered manually in Sales Force. This is both unique (the letters “ABC” are treated differently as “abc”) and External ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Source Lead Number from Empower</inlineHelpText>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Sofi_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sofi Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_To_HLR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfer To HLR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadExtensiontest1234.cls
@istest
public with sharing class LeadExtensiontest1234 {

 static testmethod void LeadExtensiontest (){ 
 
   /*     Lead testLead = new Lead();
         testlead.status = 'New';
         testlead.Channel__c ='RB Portal';
         testlead.Channel_Sources__c = 'Bank';
         testlead.firstname = 'test';
         testlead.lastname = 'lead1';
         testlead.Company = 'Test';        
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.Transfer_To_HLR__c = true;
         testlead.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead'].Id;         
         insert testlead;

         ApexPages.StandardController sc1 = new ApexPages.StandardController(testLead);
         LeadExtension ctr1 = new LeadExtension(sc1);         
         PageReference ref1= page.LeadDetail;
         ref1.getParameters().put('id', String.valueOf(testLead.Id));
         Test.setCurrentPage(ref1);
         ctr1.init();
         
         
         
         Lead testLead1 = new Lead();
         testlead1.status = 'New';
         testlead1.Channel__c ='RB Portal';
         testlead1.Channel_Sources__c = 'Bank';
         testlead1.firstname = 'test';
         testlead1.lastname = 'lead2';
         testlead1.Company = 'Test';        
         //testlead1.Is_Sofi_Lead__c = true;
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead1.Transfer_To_HLR__c = true;
         testlead1.Empower_Lead_ID__c = 'D1001390';
         //testlead1.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead'].Id;         
         insert testlead1;
         
         ApexPages.StandardController sc2 = new ApexPages.StandardController(testLead1);
         LeadExtension ctr2 = new LeadExtension(sc2);         
         PageReference ref2= page.LeadDetail;
         ref2.getParameters().put('id', String.valueOf(testLead.Id));
         Test.setCurrentPage(ref2);
         ctr2.init();
        
    */     
         
}
}