jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Notes_Type__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Notes__c.object
<CustomObject>
    <description>Sprint 3</description>
    <fields>
        <fullName>Comments_List__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>sprint 3
Wipro Technologies ltd</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>sprint 3
Wipro Technologies ltd</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Notes Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadTrgg_CL.cls
public class LeadTrgg_CL{
@future    
    public static void CO_Insertnew_Lead(Set<id> setids){
        List<Lead> listnoteLeads = new List<Lead>();
        listnoteLeads = [select id,Notes__c,Notes_Type__c from Lead where id in: setids limit 1000];
        if (!FollowUpEventHelper.hasAlreadyCreatedFollowUpLeads()) {
            Notes n = new Notes();
            n.createInsertNotes(listnoteLeads);    
            FollowUpEventHelper.setAlreadyCreatedFollowUpLeads();
        }     
    }
@future
    public static void CO_Updatenew_Lead(Set<id> setids,map<id,string> mapnotestype,map<id,string> mapnotes){
        Notes__c NewNote1;
        List<Lead> listnoteLeads = new List<Lead>();
        List<Notes__c> insertNotes = new List<Notes__c>();
        listnoteLeads = [select id,Notes__c,Notes_Type__c from Lead where id in: setids limit 1000];
        for(integer i = 0 ; i< listnoteLeads.size(); i++){                           
            if((listnoteLeads[i].Notes__c != null || listnoteLeads[i].Notes__c != '' || listnoteLeads[i].Notes_Type__c != null) &&((mapnotestype.get(listnoteLeads[i].id)!=null && listnoteLeads[i].Notes_Type__c != mapnotestype.get(listnoteLeads[i].id)) || (mapnotes.get(listnoteLeads[i].id)!=null && listnoteLeads[i].Notes__c !=  mapnotes.get(listnoteLeads[i].id))) ){
                NewNote1 = new Notes__c(
                Lead__c = listnoteLeads[i].id,               
                Comments__c = listnoteLeads[i].Notes__c,
                Comments_List__c = listnoteLeads[i].Notes_Type__c                                    
                );   
                insertNotes.add(NewNote1); 
            } 
        }
        if(insertNotes.size()>0)
            insert insertNotes; 
    }
}