jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower. In this phase, this lead number will be entered manually in Sales Force. This is both unique (the letters “ABC” are treated differently as “abc”) and External ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Source Lead Number from Empower</inlineHelpText>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Sofi_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sofi Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Lead_to_Sofi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead to Sofi</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_to_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New to Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Ref_Id__c</fullName>
        <description>Zillow quote ID</description>
        <label>Ref Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_To_HLR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfer To HLR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VFUpdate__c</fullName>
        <label>VFUpdate</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HLR</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>HLR Record Type in Leads</description>
        <label>HLR</label>
    </recordTypes>
    <recordTypes>
        <fullName>Web</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <label>Web</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadExtension.cls
public with sharing class LeadExtension {
public void init () {
}
     public Lead l {get;set;}
    public LeadExtension(Apexpages.standardController stdController) {
        this.l = (Lead)stdController.getRecord(); 
    }
   /* public void init () {
    system.debug('88888888888888');
    
        Lead ld = [select Channel_Sources__c,Channel_Values__c,id,ref_id__c,firstname,status,recordtypeid,recordtype.name,Empower_Lead_ID__c,VFUpdate__c,New_to_Active__c,Is_Sofi_Lead__c,My_Lead__c,Transfer_To_HLR__c,My_Lead_to_Sofi__c,owner.firstname,owner.lastname from lead where id =:l.id limit 1];
        recordtype rt = [select Id,Name from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead' limit 1];
        system.debug('++++++++++'+ld.recordtype.Name);
        system.debug('++++++++++'+rt.Name);
        system.debug('++++++++++'+ld.owner.firstname);
        system.debug('============='+ld.My_Lead_to_Sofi__c);
        system.debug('&&&&&&&&&&&&&&&&&&&&&1111'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&11111'+ld.New_to_Active__c);
        try{
        //added for web RecordType
        if(ld.ref_id__c != null && ld.status == 'New - Not Opened'){
        
         RecordType rt1 = [select Id,Name from RecordType where Name Like: 'Web' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.status+'#################New - not opened');
            system.debug('&&&&&&&&&&&&&&&&&&&&&222222'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&222222'+ld.New_to_Active__c);
            update ld;
         }
         
         //added for "web for send to opus" Recordtype
         else if(ld.ref_id__c != null && ld.status != 'New - Not Opened' && (ld.Empower_Lead_ID__c == null || ld.Empower_Lead_ID__c == '')){
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'Web for Send to Opus' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            system.debug('============='+ld.status+'################# NOTTTT New - not opened');
            system.debug('&&&&&&&&&&&&&&&&&&&&&222222'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&222222'+ld.New_to_Active__c);
            update ld;
         }
            
            
         else{    
                if(ld.owner.firstname == null && ld.owner.lastname == null && (ld.Empower_Lead_ID__c == null || ld.Empower_Lead_ID__c == '')){
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'Queue Lead' and SobjectType = 'Lead' limit 1];
                ld.VFUpdate__c = 'YES'; 
                ld.recordtypeId = rt1.Id;
                system.debug('@@@+++++++'+ld.recordtype.Name);
                system.debug('============='+ld.owner.firstname);
                system.debug('&&&&&&&&&&&&&&&&&&&&&222222'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&222222'+ld.New_to_Active__c);
                update ld;
            }
            else if(ld.status == 'New - Not Opened' && (ld.Empower_Lead_ID__c == null || ld.Empower_Lead_ID__c == '')) {
            if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send to empower' and SobjectType = 'Lead' limit 1];
                ld.VFUpdate__c = 'YES'; 
                ld.recordtypeId = rt1.Id;
                system.debug('@@@+++++++'+ld.recordtype.Name);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                system.debug('&&&&&&&&&&&&&&&&&&&&&222222'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&222222'+ld.New_to_Active__c);
                update ld;
                }
               else{
                ld.recordtypeid =rt.Id;
                ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
                system.debug('++++++++++'+ld);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                update ld;
                system.debug('++++++++++'+ld.recordtype.Name); 
                system.debug('&&&&&&&&&&&&&&&&&&&&&333333'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&333333'+ld.New_to_Active__c);
                }
            }
           
           
            
             else if(ld.status != 'New - Not Opened' && (ld.Empower_Lead_ID__c == null || ld.Empower_Lead_ID__c == '') && ld.Transfer_To_HLR__c == true) { 
             if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send to empower Unlock HLR Lead Id' and SobjectType = 'Lead' limit 1];
                ld.VFUpdate__c = 'YES'; 
                ld.recordtypeId = rt1.Id;
                system.debug('@@@+++++++'+ld.recordtype.Name);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                update ld;
                }
             else{  
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'No Send to empower Unlock HLR Lead Id' and SobjectType = 'Lead' limit 1]; 
                ld.recordtypeid = rt1.Id;
                ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
                system.debug('++++++++++'+ld.recordtype.Name);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                update ld;
                }
            }
          
               
            else if(ld.status != 'New - Not Opened' && (ld.Empower_Lead_ID__c == null || ld.Empower_Lead_ID__c == '' ) && ld.Transfer_To_HLR__c == false) {  // new logic added for New lead 
               if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB MC Send to empower when HLR true' and SobjectType = 'Lead' limit 1];
                ld.VFUpdate__c = 'YES'; 
                ld.recordtypeId = rt1.Id;
                system.debug('@@@+++++++'+ld.recordtype.Name);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                update ld;
                }
               else{
                RecordType rt1 = [select Id,Name from RecordType where Name Like: 'MC_Send_to_empower_when_HLR_true' and SobjectType = 'Lead' limit 1];
                ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
                ld.recordtypeId = rt1.Id;
                system.debug('++++++++++'+ld.recordtype.Name);
                system.debug('============='+ld.My_Lead_to_Sofi__c);
                update ld;
                }
            }
       }
       }
       catch(Exception e){
       system.debug('Error is found in the following line'+e);
     }

      try{
       string emp = ld.Empower_Lead_ID__c;
        if (emp != null ) {
        System.debug('++Test' + ld.status +'Test1'+ ld.Empower_Lead_ID__c + 'Test2' +ld.Is_Sofi_Lead__c);
        
        
        //added for "web for view in opus" Recordtype
        if(ld.ref_id__c != null && ld.status != 'New - Not Opened'){
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'Web for View in Opus' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            system.debug('&&&&&&&&&&&&&&&&&&&&&222222'+ld.VFUpdate__c+'&&&&&&&&&&&&&&&&&&&&&222222'+ld.New_to_Active__c);
            update ld;
         }


        else if(ld.status == 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == false) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
         system.debug('@@@++++++++entered if');
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send to empower1' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
           system.debug('@@@+++++++'+ld.recordtype.Name);
            }
        else{  
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'No_Send_to_empower1' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt1.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++entered 1+++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;     
            }       
            }
          //Added for sprint 6B  
        else if(ld.status == 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == true ) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
            system.debug('@@@enterdif');
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            }
         else{   
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'No send to empower in My Sofi Leads' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt1.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++entered 1+++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;       
            }     
            }
            
        else if(ld.status != 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == false && ld.My_Lead__c == false) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
             system.debug('@@@Entered if+++++++');
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            }
         else{
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'No send to empower in My Sofi Leads' and SobjectType = 'Lead' limit 1]; // Changed from No_Send_to_empower2
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;   
            }   
        } 
        
        else if(ld.status != 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == true && ld.Transfer_to_HLR__c == true) { // Removed  || emp.startswith('E')
        
            if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
            system.debug('@@@entered if');
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            }
            else{
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('@@@entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;   
            }   
        }
        
        else if(ld.status != 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == false && ld.My_Lead__c == true && ld.Transfer_To_HLR__c == true) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
            system.debug('@@@entered if');
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            }
          else{
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;  
            }    
        }  
        else if(ld.status != 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == false && ld.My_Lead__c == true && ld.Transfer_To_HLR__c == false && ld.My_Lead_to_Sofi__c == true) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No Send to empower2' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            }
         else{
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'No_Send_to_empower2' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;    
            }  
        }
        
        else if(ld.status != 'New - Not Opened' && emp.startswith('D') && ld.Is_Sofi_Lead__c == false && ld.My_Lead__c == true && ld.Transfer_To_HLR__c == false && ld.My_Lead_to_Sofi__c == false) { // Removed  || emp.startswith('E')
        if (( ld.Channel_Sources__c =='Bank' && ld.Channel_Values__c =='RB Portal') || ( ld.Channel_Sources__c =='Direct 360' &&( ld.Channel_Values__c =='Inbound' ||ld.Channel_Values__c =='Outbound' ))) {
            RecordType rt1 = [select Id,Name from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads without HLR' and SobjectType = 'Lead' limit 1];
            ld.VFUpdate__c = 'YES'; 
            ld.recordtypeId = rt1.Id;
            system.debug('@@@+++++++'+ld.recordtype.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;
            }
         else{
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'No send to empower in My Sofi Leads without HLR' and SobjectType = 'Lead' limit 1]; // changed  back from 'No send to empower in My Sofi Leads'
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;   
            }   
        }
        
        else if(emp.startswith('E')) {
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            RecordType rt2 = [select Id,Name from RecordType where Name Like: 'For_My_loans' and SobjectType = 'Lead' limit 1];
            ld.recordtypeId = rt2.Id;
            ld.VFUpdate__c = 'YES';  //Added for sprint 6B 
           // ld.Is_Sofi_Lead__c = true;
            system.debug('+++++ entered 2+++++'+ld.recordtype.Name);
            system.debug('+++++ entered 2+++++'+rt2.Name);
            system.debug('============='+ld.My_Lead_to_Sofi__c);
            update ld;   
             
        }
        }
       }
 catch(Exception e){
      system.debug('Error is found in the following line'+e);
     }
    }*/
}