jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Notes__c.object
<CustomObject>
    <description>Sprint 3</description>
    <fields>
        <fullName>Comments_List__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>sprint 3
Wipro Technologies ltd</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Notes Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_Notes_CL.cls
/**
* @Created By : Leena (Wipro),   @Created Date : 10 Aug 2012
* @Last Modified By : Leena (Wipro),  @Modified Date : 11 Sep 2012
* @description : This class is used to create a new note
*                 
**/
public class CO_Notes_CL{
    public Notes__c note{set; get;}
    public id LeadId{get; set;}
    
    public CO_Notes_CL(ApexPages.StandardSetController controller){
        LeadId= system.currentPageReference().getParameters().get('id');
        note= new Notes__c();
        note.Lead__c = Leadid;
    }
    //Method to save the new Note record
    public PageReference SaveNote(){
        try{
            if(Note.Comments_List__c!=null){
            insert note;
             PageReference pr = new PageReference('/' + LeadId);  
             pr.setRedirect(true);  
             return pr;
             }
             else{
                  ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL,'Enter Notes Type')); 
                  return null;
             }
         }
         catch(Exception e){}
         return null;
    }
     //Method to return to lead page
    public PageReference Cancel(){
        return (new pageReference('/' +LeadId));
    }
}