jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <description>This is to specify the loan type of the lead.</description>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Round_robin_status__c</fullName>
        <label>Round Robin status</label>
        <picklist>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round_robin_time__c</fullName>
        <inlineHelpText>Time in Mins</inlineHelpText>
        <label>Round Robin Wait time</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>RRB Queue Matrix</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Member__c.object
<CustomObject>
    <fields>
        <fullName>Queue_member_proficiency__c</fullName>
        <label>Queue member proficiency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RRB_Queue_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRB Queue Matrix</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>RRB Queue Members</relationshipLabel>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RRB Queue Member</label>
    <nameField>
        <label>RRB Queue Members  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Scheduler__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_User_ID__c</fullName>
        <label>Current User ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_User_Name__c</fullName>
        <label>Current User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Limit__c</fullName>
        <label>Lead Limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_User_Id__c</fullName>
        <label>Next User Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_User_Name__c</fullName>
        <label>Next User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue Name</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>Schedulers</relationshipLabel>
        <relationshipName>Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Proficiency_Level__c</fullName>
        <description>To fetch value from Queue Members.</description>
        <label>Current User Proficiency Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scheduler</label>
    <nameField>
        <label>Scheduler Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlimited_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlimited Leads</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/RoundRobinScheduler_Test.cls
@istest
public class RoundRobinScheduler_Test{
Static TestMethod Void Test_SchedulerClass_Test(){

Group q = new Group();
q.Name = 'South-Central – Purchase';
q.type = 'Queue';
insert q;
QueueSobject testSQueue = new QueueSObject(QueueId = q.Id, SobjectType = 'Lead');

    System.runAs(new User(Id = UserInfo.getUserId())) {   
    insert testSQueue;
}

User u = [Select id,name,OOO__c,Lead_limit__c,Count__c,Last_assigned__c from user where id =: userInfo.getUserid() limit 1];
u.Lead_limit__c = 1;
update u;

Profile dmc = [select profile.Id from profile where profile.Name = 'Centralized Loan Officer' limit 1];

User u2 = new user();
u2.FirstName = 'test';
u2.LastName = 'last';
u2.email = 'test@test.com';
u2.ProfileId = dmc.id;
u2.Username = 'testuser@tst.com';
u2.Alias = 'test';
u2.CommunityNickname = 'testtesttest';
u2.TimeZoneSidKey = 'America/Chicago';
u2.LocaleSidKey = 'en_US';
u2.EmailEncodingKey = 'ISO-8859-1';
u2.LanguageLocaleKey = 'en_US';
//u2.IsActive = true;
//u2.Unlimited_Leads__c = true;
u2.Lead_limit__c = 1;
insert u2;



RRB_Queue_Matrix__c testQueue = new RRB_Queue_Matrix__c();
testQueue.name = 'South-Central – Purchase';
testQueue.Round_robin_status__c = 'W';
testQueue.Round_robin_time__c = 0; 
insert testQueue ;

RRB_Queue_Member__c testMember1 = new RRB_Queue_Member__c();
testMember1.name = u.name;
testMember1.Queue_member_proficiency__c =1;
testMember1.RRB_Queue_Matrix__c = testQueue.id;
testMember1.user__c = u.id;
insert testMember1;

testMember1 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember1.id];
system.debug('***********memberQueue'+testMember1.RRB_Queue_Matrix__r.name);
system.debug('***********memberQueue'+testMember1.user__r.name);

RRB_Queue_Member__c testMember2 = new RRB_Queue_Member__c();
testMember2.name = u.name;
testMember2.Queue_member_proficiency__c =2;
testMember2.RRB_Queue_Matrix__c = testQueue.id;
testMember2.user__c = u.id;
insert testMember2;

testMember2 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember2.id];
system.debug('***********member2Queue'+testMember2.RRB_Queue_Matrix__r.name);
system.debug('***********member2User'+testMember2.user__r.name);

RRB_Queue_Member__c testMember3 = new RRB_Queue_Member__c();
testMember3.name = u2.name;
testMember3.Queue_member_proficiency__c =2;
testMember3.RRB_Queue_Matrix__c = testQueue.id;
testMember3.user__c = u2.id;
insert testMember3;

testMember3 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember3.id];
system.debug('***********member3Queue'+testMember3.RRB_Queue_Matrix__r.name);
system.debug('***********member3User'+testMember3.user__r.name);


SchedulerClass sc = new SchedulerClass();
sc.TestRun();

ResetDailyCount rdc= new ResetDailyCount();
rdc.reset();

List<Scheduler__c> TSchedule = [SELECT Count__c,Current_User_ID__c,Current_User_Name__c,Id,Last_Assigned__c,Lead_Limit__c,Name,Next_User_Id__c,Next_User_Name__c,OOO__c,Queue_Name__c,User_Proficiency_Level__c FROM Scheduler__c];

Lead l = new lead(ownerid = q.id);
l.Channel__c = 'Centralized Retail';
l.Channel_Sources__c = 'Bank';
l.Channel_Values__c = 'RB Portal';
l.FirstName='test';
l.LastName= 'Lead' ;
l.Email='test@test.com';
l.Borrowers_Current_Residence__c='Own';
l.Company='NA';
l.Property_State__c='CA';
l.Loan_Type__c='Conventional';
l.Occupancy_Code__c='Owner Occupied';
l.Property_Type__c='SFR Detached';
l.Value_of_Home__c=300000;
l.loan_Purpose__c='Purchase';
l.Requested_Loan_Amount__c=100000;
l.Department__c ='South-Central';
l.Is_assigned_already__c = false;
insert l;


l = [SELECT Id,Name,OwnerId,Owner.Name,Is_assigned_already__c,CreatedDate  From Lead Where id =:l.id];
system.debug('***********leadOwnerName'+l+'The owner name is' +l.owner.name);

RoundRobinScheduler rrc = new RoundRobinScheduler();
rrc.testMethodRun();

Lead l2 = new lead(ownerid = q.id);
l2.Channel__c = 'Centralized Retail';
l2.Channel_Sources__c = 'Bank';
l2.Channel_Values__c = 'RB Portal';
l2.FirstName='test';
l2.LastName= 'Lead' ;
l2.Email='test@test.com';
l2.Borrowers_Current_Residence__c='Own';
l2.Company='NA';
l2.Property_State__c='CA';
l2.Loan_Type__c='Conventional';
l2.Occupancy_Code__c='Owner Occupied';
l2.Property_Type__c='SFR Detached';
l2.Value_of_Home__c=300000;
l2.loan_Purpose__c='Purchase';
l2.Requested_Loan_Amount__c=100000;
l2.Department__c ='South-Central';
//l2.ownerid = q.id;
l2.Is_assigned_already__c = false;
insert l2;

l2 = [SELECT Id,Name,OwnerId,Owner.Name,Is_assigned_already__c,CreatedDate  From Lead Where id =:l2.id];
system.debug('***********leadOwnerName'+l2+'The owner name is' +l2.owner.name);


u.count__c = 12;
update u;

RoundRobinScheduler rrc2 = new RoundRobinScheduler();
rrc2.testMethodRun();
 }
}