jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Prequal</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>Standard Record Type for users creating leads and for leads that haven&apos;t been converted</description>
        <label>Prequal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is the channel from which the lead was generated</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <label>Loan Purpose</label>
        <picklist>
            <controllingField>Loan_Type__c</controllingField>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streamline Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRRRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Hot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/StatusRatingMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping for Rating</description>
    <fields>
        <fullName>Default_Mapping_Fields_Name__c</fullName>
        <inlineHelpText>mapping field = lead/opp field eg: Stage__c=Stagename</inlineHelpText>
        <label>Default Mapping Fields Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanPurpose__c</fullName>
        <label>Loan Purpose</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <inlineHelpText>Please enter the Semicolon-separated values only. eg Lead;Opportunity</inlineHelpText>
        <label>Object Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_to_Apply__c</fullName>
        <label>Time to Apply</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>StatusRatingMapping</label>
</CustomObject>

jvimalprasathdev/src/classes/UpdateRating_Test.cls
@isTest
private class UpdateRating_Test {
	
	static void init(){
		List<StatusRatingMapping__c> settingList = new List<StatusRatingMapping__c>();
    	settingList.add(new StatusRatingMapping__c (Name='1', Object_Name__c='Lead;Opportunity', LoanPurpose__c='Purchase;Ref', Status__c='Request For Prequal;Contacted / No Product Available;Contacted / No Longer Interested', Stage__c='Any',Time_to_Apply__c='Any',Rating__c='Cold1',Is_Default__c=false,Default_Mapping_Fields_Name__c=''));
    	settingList.add(new StatusRatingMapping__c (Name='2', Object_Name__c='Opportunity', LoanPurpose__c='Purchase;Ref', Status__c='Contacted / No Longer Interested', Stage__c='Lost',Time_to_Apply__c='Any',Rating__c='Dead',Is_Default__c=false,Default_Mapping_Fields_Name__c=''));
    	settingList.add(new StatusRatingMapping__c (Name='3', Object_Name__c='Opportunity', LoanPurpose__c='Ref', Status__c='any', Stage__c='Any',Time_to_Apply__c='Any',Rating__c='Cold11',Is_Default__c=false,Default_Mapping_Fields_Name__c=''));
    	settingList.add(new StatusRatingMapping__c (Name='4', Object_Name__c='Opportunity', LoanPurpose__c='Purchase', Status__c='Request For Prequal', Stage__c='Prospecting',Time_to_Apply__c='Any',Rating__c='Cold2',Is_Default__c=false,Default_Mapping_Fields_Name__c=''));
    	settingList.add(new StatusRatingMapping__c (Name='5', Object_Name__c='Opportunity', LoanPurpose__c='Refi', Status__c='Contacted / Still Deciding', Stage__c='Prospecting',Time_to_Apply__c='1-2 weeks',Rating__c='Hot',Is_Default__c=false,Default_Mapping_Fields_Name__c=''));
    	settingList.add(new StatusRatingMapping__c (Name='6', Object_Name__c='Opportunity', LoanPurpose__c='', Status__c='', Stage__c='Prospecting',Time_to_Apply__c='',Rating__c='Hot1',Is_Default__c=true,Default_Mapping_Fields_Name__c='Stage__c=Stagename'));
    	settingList.add(new StatusRatingMapping__c (Name='7', Object_Name__c='Opportunity', LoanPurpose__c='any', Status__c='', Stage__c='any',Time_to_Apply__c='',Rating__c='Cold3',Is_Default__c=true,Default_Mapping_Fields_Name__c='Stage__c=StageName;LoanPurpose__c=Loan_Purpose__c'));
    	settingList.add(new StatusRatingMapping__c (Name='8', Object_Name__c='Opportunity', LoanPurpose__c='', Status__c='', Stage__c='Lost',Time_to_Apply__c='',Rating__c='Hot2',Is_Default__c=true,Default_Mapping_Fields_Name__c='Stage__c=Stagename'));
    	settingList.add(new StatusRatingMapping__c (Name='9', Object_Name__c='Opportunity', LoanPurpose__c='', Status__c='', Stage__c='Lost',Time_to_Apply__c='',Rating__c='Hot3',Is_Default__c=true,Default_Mapping_Fields_Name__c='Stage__c=StageName;LoanPurpose__c=Loan_Purpose__c'));
    	settingList.add(new StatusRatingMapping__c (Name='10', Object_Name__c='Opportunity', LoanPurpose__c='', Status__c='', Stage__c='Lost',Time_to_Apply__c='',Rating__c='Cold4',Is_Default__c=true,Default_Mapping_Fields_Name__c='Stage__c=Stagename'));
    	
    	insert settingList;
	}
	
	static testMethod void myUnitTest_UpdateRating() {
		init();
		try{
			Lead ld = new lead();
			ld.status = 'Request For Prequal';
			ld.Channel__c = 'Centralized Retail';
			ld.Channel_Sources__c = 'Bank';
			ld.Applicant_Type__c = 'Individual';
			ld.Channel_Values__c = 'RB Portal';
			ld.Internal_Referral__c = 'N/A';
			ld.Borrowers_Current_Residence__c =  'Own';
			ld.Company = 'None';
			ld.FirstName = 'sunil';
			ld.LastName = 'testrec';
			ld.Borrowers_Home_Phone__c = '(111) 222-3333';
			//ld.Internal_Referral_Name__c = u.id;
			ld.Property_State__c = 'TX';
			ld.Notes_Type__c = 'Called Home, Left Message – No Contact';
			ld.Loan_Purpose__c = 'Purchase';
			ld.Lead_Stage__c='Lost';
			ld.Shopping_Stage__c='1-2 weeks';
			
			insert ld;
			List<Lead> ldList = new List<Lead>();
			ldList.add(ld);
			UpdateRatings.getLeadRatings(ldList);
			
			
		   account acc =  new account(lastname='Testuser');
	       insert acc;
	      
	       Opportunity opp = new Opportunity(accountid=acc.id,name = 'test name',Loan_Purpose__c='Purchage',Loan_Status__c='Contacted / Still Deciding',StageName='Prospecting',Shopping_Stage__c='1-2 weeks',CloseDate=System.today(),Related_Lead__c = null); 
	       insert opp;
			
			List<Opportunity> oppList = new List<Opportunity>();
			oppList.add(opp);
			UpdateRatings.getOppRatings(oppList);
			opp.Loan_Purpose__c='Purchage1';
			update opp;
			UpdateRatings.getOppRatings(oppList);
			
			
		   Opportunity opp1 = new Opportunity(Related_Lead__c = ld.id, accountid=acc.id,name = 'test name1',Loan_Purpose__c='Purchage',Loan_Status__c='Contacted / Still Deciding',StageName='Prospecting',Shopping_Stage__c='1-2 weeks',CloseDate=System.today()); 
	       insert opp1;
			
		}catch(Exception e){
			System.debug('Error during test run: ' + e);
		}
		
	}
}