jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Product_Preferences__c</fullName>
        <label>Product Preferences</label>
        <picklist>
            <picklistValues>
                <fullName>5/1 Adjustable Rate Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>7/1 Adjustable Rate Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>15 Year Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>30 Year Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Preference</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA 15 Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA 30 Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL 10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL 15</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL 20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC 20</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC 30</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Product_Preference_Mapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Mapping_Value__c</fullName>
        <description>The Value entered here should match the Pick List Value of Product Preference in Lead Object</description>
        <label>Mapping Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Product Preference Mapping</label>
</CustomObject>

jvimalprasathdev/src/classes/LeadProductMapping.cls
/*
Name: LeadProductMapping
Author: Vimal 
Description: This Class update the Product Preference field for the record which are coming from Sofi according to Custom Setting "Product Preference Mapping" Values
For the story #B493593
*/

public class LeadProductMapping {
	
	public void leadProductPreferenceMapping (List<Lead> Leads){
		
		try {
			
		for(Lead tmpLead: leads){
			String tmpProductPreference='';  
			
			for(String splitProductPreference : tmpLead.Product_Preferences__c.split(';')){ 
				Product_Preference_Mapping__C tmpProductMapping=Product_Preference_Mapping__C.getInstance(splitProductPreference.trim()); 
				
				if(tmpProductMapping!=null){                
				   tmpProductPreference=tmpProductPreference+tmpProductMapping.Mapping_Value__c+';'; 
				}            
				     
			}
			    
			if(tmpProductPreference!=''){         
			   TmpLead.Product_Preferences__c=tmpProductPreference.trim();             
			}
			
		}
		
	  }
	  Catch(Exception e){
	  system.debug('Exception thrown while performing Product Preference Mapping'+e);
	  }
	  
	}//End of Method LeadProductPreferenceMapping

}//End of Class LeadProductMapping