jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Aggregator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_property_value__c</fullName>
        <label>Estimated property value</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>How_Would_you_Describe_Your_Credit__c</fullName>
        <label>Your estimated credit score</label>
        <picklist>
            <picklistValues>
                <fullName>740-800</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>720-739</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>700-719</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>680-699</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>660-679</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>580-659</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than 580</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Less than 660</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Amount1__c</fullName>
        <label>Loan Amount</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <description>This is to specify the loan type of the lead.</description>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Postal_Code__c</fullName>
        <description>This is to specify property zip.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property Zip/ Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Amount__c</fullName>
        <description>This is to specify the requested loan amount in dollars.</description>
        <label>Requested Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Shopping_Stage__c</fullName>
        <label>When do you intend to apply?</label>
        <picklist>
            <picklistValues>
                <fullName>1-2 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-2 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4+ months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Utm_FormVersion__c</fullName>
        <label>Utm_FormVersion</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Utm_SourceURL__c</fullName>
        <label>Utm_SourceURL</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Value_of_Home__c</fullName>
        <description>This is to specify the value of home in dollars.</description>
        <label>Estimated property value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>utm_campaign__c</fullName>
        <label>utm_campaign</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_content__c</fullName>
        <label>utm_content</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_medium__c</fullName>
        <label>utm_medium</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_source__c</fullName>
        <label>utm_source</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>utm_term__c</fullName>
        <label>utm_term</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Web</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <label>Web</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/HomeLoanWTLController_CLS.cls
/*
Description: Get the lead details for Site form and Insert Lead.
Created by: Hari
Last Modified: 8/17/2013 
*/

public with sharing class HomeLoanWTLController_CLS {

    public lead TLead ;
    public Recordtype WebRecordType;
    
    
    public HomeLoanWTLController_CLS(){
        try{
            TLead = new Lead();        
            if(ApexPages.currentPage().getParameters().get('Utm_campaign') != null)
                TLead.utm_campaign__c = ApexPages.currentPage().getParameters().get('Utm_campaign');
            if(ApexPages.currentPage().getParameters().get('Utm_content') != null)
                TLead.utm_content__c = ApexPages.currentPage().getParameters().get('Utm_content');
            if(ApexPages.currentPage().getParameters().get('Utm_medium') != null)
                TLead.utm_medium__c = ApexPages.currentPage().getParameters().get('Utm_medium');
            if(ApexPages.currentPage().getParameters().get('Utm_source') != null)
                TLead.utm_source__c = ApexPages.currentPage().getParameters().get('Utm_source');
            if(ApexPages.currentPage().getParameters().get('Utm_term') != null)
                TLead.utm_term__c = ApexPages.currentPage().getParameters().get('Utm_term');
            if(ApexPages.currentPage().getParameters().get('Utm_formversion') != null)
                TLead.Utm_FormVersion__c = ApexPages.currentPage().getParameters().get('Utm_formversion');                                                            
            //system.debug('&&&&&&&&&&&&&&'+TLead);
         }Catch(Exception e){
             //Error
         }
    }
    

    
    public PageReference SaveLead(){
        try
        {
        
        system.debug('&&&&&&&&&&&&&&'+ApexPages.currentPage().getUrl());
            //get the lead Record type - Web. Needs to be assigned to Lead.
            WebRecordType = [select id from recordtype where name = 'Web' limit 1];        
            
            //Set default assignment rule to True
            Database.DMLOptions dmo = new Database.DMLOptions();
            dmo.assignmentRuleHeader.useDefaultRule= true;
            
            // fetch the values from visualforce page form.
            //Mapping Loan Purpose
            if(ApexPages.currentPage().getParameters().get('loan_type') == 'Buy a Home')
                TLead.Loan_Purpose__c = 'Purchase' ;
            if(ApexPages.currentPage().getParameters().get('loan_type') == 'Mortgage Refinance')
                TLead.Loan_Purpose__c = 'Rate & Term Refinance' ;
            if(ApexPages.currentPage().getParameters().get('loan_type') == 'Cash-Out Refinance')
                TLead.Loan_Purpose__c = 'Cash-out Refinance' ; 
                             
            //TLead.Loan_Amount1__c = '$' + ApexPages.currentPage().getParameters().get('hidden_loan_amount');                
            //TLead.Requested_Loan_Amount__c = decimal.valueOf(ApexPages.currentPage().getParameters().get('hidden_loan_amount'));
            //TLead.Estimated_property_value__c ='$' + ApexPages.currentPage().getParameters().get('hidden_estimated_value');
            TLead.Requested_Loan_Amount__c = decimal.valueOf(ApexPages.currentPage().getParameters().get('hidden_loan_amount'));
            TLead.Value_of_Home__c = decimal.valueOf(ApexPages.currentPage().getParameters().get('hidden_estimated_value'));
            //TLead.Estimated_property_value__c ='$' + ApexPages.currentPage().getParameters().get('hidden_estimated_value');
            
            TLead.Loan_Type__c = 'Conventional';
            //Mapping Credit Scores.
            if(ApexPages.currentPage().getParameters().get('credit_score') == 'Excellent (740+)')
                TLead.How_Would_you_Describe_Your_Credit__c = '740-800' ;
            else if(ApexPages.currentPage().getParameters().get('credit_score') == 'Very Good (720-739)')
                TLead.How_Would_you_Describe_Your_Credit__c = '720-739' ; 
            else if(ApexPages.currentPage().getParameters().get('credit_score') == 'Good (700-719)')
                TLead.How_Would_you_Describe_Your_Credit__c = '700-719' ;  
            else if(ApexPages.currentPage().getParameters().get('credit_score') == 'Fair (680-699)')
                TLead.How_Would_you_Describe_Your_Credit__c = '680-699' ;  
            else if(ApexPages.currentPage().getParameters().get('credit_score') == 'Less than 680')
                    TLead.How_Would_you_Describe_Your_Credit__c = 'Less than 660' ;                                                             
            
            
            TLead.Shopping_Stage__c = ApexPages.currentPage().getParameters().get('when_apply');
            TLead.Property_Zip_Postal_Code__c = ApexPages.currentPage().getParameters().get('zip_code');
            TLead.FirstName = ApexPages.currentPage().getParameters().get('first_name');
            TLead.LastName = ApexPages.currentPage().getParameters().get('last_name');
            TLead.Phone = ApexPages.currentPage().getParameters().get('phone');
            TLead.Email = ApexPages.currentPage().getParameters().get('email');         
            TLead.RecordTypeId = WebRecordType.id;
            TLead.Channel__c = 'Centralized Retail';
            TLead.Company = 'N/A';
            TLead.Property_State__c = 'NA';
            TLead.Channel_Values__c = 'Lead Aggregator';
            
            if(ApexPages.currentPage().getParameters().get('Source_URL') != null)
            TLead.Utm_SourceURL__c = ApexPages.currentPage().getParameters().get('source_url');  
            //system.debug('&&&&&&&&&&&&&&'+TLead);
            TLead.setOptions(dmo);        
            //system.debug('&&&&&&&&&&&&&&'+ApexPages.currentPage().getUrl());
            insert TLead;
            
            //Redirect to Confirmation screen on Complete
            PageReference page = new PageReference('/apex/Confirmation');
            page.setRedirect(true);
            return page;
            }catch(Exception e)
            {
                return null;
            }
            
        
    }
    
}