jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of co-borrower’s address.</description>
        <label>Co-Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Email__c</fullName>
        <description>This is to specify co-borrower’s email address.</description>
        <label>Co-Borrowers Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_First_Name__c</fullName>
        <description>This is to specify the co-borrower’s first name.</description>
        <label>Co-Borrowers First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Home_Phone__c</fullName>
        <description>This is to specify co-borrower’s home phone.</description>
        <label>Co-Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Last_Name__c</fullName>
        <description>This is to specify the co-borrower’s last name.</description>
        <label>Co-Borrowers Last Name</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_Borrower_Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrower Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copy_Borrowers_Home_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrowers Home Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Bank Region</label>
        <picklist>
            <picklistValues>
                <fullName>Mid-Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South-Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North-East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Is_assigned_already__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is assigned already</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <description>This is to specify the loan type of the lead.</description>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>This is to specify the property type of the lead.</description>
        <label>Property Type</label>
        <picklist>
            <picklistValues>
                <fullName>SFR Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFR Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-Rise (1-4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Rise (5-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High-Rise (9+)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Townhome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Amount__c</fullName>
        <description>This is to specify the requested loan amount in dollars.</description>
        <label>Requested Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Value_of_Home__c</fullName>
        <description>This is to specify the value of home in dollars.</description>
        <label>Estimated property value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/UpdateLeadDetails_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class UpdateLeadDetails_Test {

    static testMethod void myUnitTest() {
        
        
        Lead l = new lead();
        l.Channel__c = 'Centralized Retail';
        l.Channel_Sources__c = 'Bank';
        l.Channel_Values__c = 'RB Portal';
        l.FirstName='test';
        l.LastName= 'Lead' ;
        l.Email='test@test.com';
        l.Borrowers_Current_Residence__c='Own';
        l.Company='NA';
        l.Property_State__c='CA';
        l.Loan_Type__c='Conventional';
        l.Occupancy_Code__c='Owner Occupied';
        l.Property_Type__c='SFR Detached';
        l.Value_of_Home__c=300000;
        l.loan_Purpose__c='Purchase';
        l.Requested_Loan_Amount__c=100000;
        l.Department__c ='South-Central';
        //l.ownerid = q.id;
        l.Is_assigned_already__c = false;
        l.Copy_Borrower_Current_Address__c = true;
        l.Co_Borrowers_First_Name__c ='test';
        l.Co_Borrowers_Last_Name__c = 'test';
        l.Co_Borrowers_Address_1__c = 'test';
        l.Borrowers_Address_1__c = 'nottest';
        l.Copy_Borrowers_Home_Phone__c = true;
        l.Co_Borrowers_Home_Phone__c = '(999) 999-9999';
        insert l;
        
        
        Lead l2 = new lead();
        l2.Channel__c = 'Centralized Retail';
        l2.Channel_Sources__c = 'Bank';
        l2.Channel_Values__c = 'RB Portal';
        l2.FirstName='test2';
        l2.LastName= 'Lead2' ;
        l2.Email='test@test2.com';
        l2.Borrowers_Current_Residence__c='Own';
        l2.Company='NA';
        l2.Property_State__c='CA';
        l2.Loan_Type__c='Conventional';
        l2.Occupancy_Code__c='Owner Occupied';
        l2.Property_Type__c='SFR Detached';
        l2.Value_of_Home__c=300000;
        l2.loan_Purpose__c='Purchase';
        l2.Requested_Loan_Amount__c=100000;
        l2.Department__c ='South-Central';
        //l.ownerid = q.id;
        l2.Is_assigned_already__c = false;
        l2.Copy_Borrower_Current_Address__c = true;
        l2.Co_Borrowers_First_Name__c ='test';
        l2.Co_Borrowers_Last_Name__c = 'test';
        l2.Co_Borrowers_Address_1__c = null;
        l2.Borrowers_Address_1__c = 'nottest';
        l2.Copy_Borrowers_Home_Phone__c = true;
        l2.Co_Borrowers_Home_Phone__c = null;
        l2.Co_Borrowers_Email__c = 'test@test.com';
        insert l2;
        
        List<lead> listLeads = [select id,Copy_Borrower_Current_Address__c,Co_Borrowers_Address_1__c,Copy_Borrowers_Home_Phone__c,Co_Borrowers_Home_Phone__c
        from lead where id =: l.id OR id =: l2.id];
        
        UpdateLeadDetails ULD = new UpdateLeadDetails();
        ULD.updateAddressAndPhone(listLeads);    
        
        
    }
}