jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Department__c</fullName>
        <label>Bank Region</label>
        <picklist>
            <picklistValues>
                <fullName>Mid-Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South-Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>North-East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower. In this phase, this lead number will be entered manually in Sales Force. This is both unique (the letters “ABC” are treated differently as “abc”) and External ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Source Lead Number from Empower</inlineHelpText>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Sofi_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sofi Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>My_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Lead_to_Sofi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead to Sofi</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_to_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>New to Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_To_HLR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfer To HLR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VFUpdate__c</fullName>
        <label>VFUpdate</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>HLR</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>HLR Record Type in Leads</description>
        <label>HLR</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadExtension_Test.cls
@istest
public class LeadExtension_Test{

/* public static testmethod void test_Lead_Extension0(){
    
     Database.DMLOptions dmo = new Database.DMLOptions();
     dmo.assignmentRuleHeader.useDefaultRule= true;
        Lead TestLead = new Lead();    
        TestLead.channel__c = 'Centralized Retail';  
        TestLead.Channel_Sources__c = 'Bank';
        TestLead.Channel_Values__c = 'RB Portal';
        TestLead.loan_purpose__c = 'Purchase';
        TestLead.department__c = 'Mid-Atlantic';
        TestLead.FirstName = 'ABCD';
        TestLead.Status = 'New - Not Opened';
        TestLead.VFUpdate__c = 'Yes';
        TestLead.New_to_Active__c = true;
        TestLead.Is_Sofi_Lead__c = true;
        TestLead.My_Lead__c = true;
        TestLead.Transfer_To_HLR__c = true;
        TestLead.My_Lead_to_Sofi__c = true;
        TestLead.Empower_Lead_ID__c = '';
        TestLead.Property_State__c = 'TX';
        TestLead.LastName = 'ABCD';
        TestLead.Company = 'ABCD';
        TestLead.setOptions(dmo);
        TestLead.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead;
        
        
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',TestLead.id);
         ApexPages.StandardController sc1 = new ApexPages.standardController(TestLead);
         LeadExtension Cntlr1 = new LeadExtension(sc1);
         Cntlr1.init();
    
    } 


    public static testmethod void test_Lead_Extension(){
        //Positive TestLead
        Lead TestLead = new Lead();
        TestLead.Channel_Sources__c = 'Bank';
        TestLead.Channel_Values__c = 'RB Portal';
        TestLead.FirstName = 'ABCD';
        TestLead.Status = 'New - Not Opened';
        TestLead.VFUpdate__c = 'Yes';
        TestLead.New_to_Active__c = true;
        TestLead.Is_Sofi_Lead__c = true;
        TestLead.My_Lead__c = true;
        TestLead.Transfer_To_HLR__c = true;
        TestLead.My_Lead_to_Sofi__c = true;
        TestLead.Empower_Lead_ID__c = '';
        TestLead.Property_State__c = 'TX';
        TestLead.LastName = 'ABCD';
        TestLead.Company = 'ABCD';
        TestLead.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead;
        
        TestLead.Channel_Sources__c = 'Direct 360';
        TestLead.Channel_Values__c = 'Inbound';
        update TestLead;
        
            
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',TestLead.id);
         ApexPages.StandardController sc1 = new ApexPages.standardController(TestLead);
         LeadExtension Cntlr1 = new LeadExtension(sc1);
         Cntlr1.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'New - Not Opened';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = true;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = '';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send to empower' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
    }  
    static testmethod void test_Lead_Extension1()
    {
        Lead TestLead1 = new Lead();
        TestLead1.Channel_Sources__c = 'Bank';
        TestLead1.Channel_Values__c = 'RB Portal';
        TestLead1.FirstName = 'ABCD';
        TestLead1.Status = 'Active';
        TestLead1.VFUpdate__c = 'Yes';
        TestLead1.New_to_Active__c = true;
        TestLead1.Is_Sofi_Lead__c = true;
        TestLead1.My_Lead__c = true;
        TestLead1.Transfer_To_HLR__c = true;
        TestLead1.My_Lead_to_Sofi__c = true;
        TestLead1.Empower_Lead_ID__c = '';
        TestLead1.Property_State__c = 'TX';
        TestLead1.LastName = 'ABCD';
        TestLead1.Company = 'ABCD';
        TestLead1.RecordTypeId = [select Id from RecordType where Name Like: 'RB MC Send to empower when HLR true' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead1;
        
        TestLead1.Channel_Sources__c = 'Direct 360';
        TestLead1.Channel_Values__c = 'Inbound';
        update TestLead1;
        
         PageReference ref1= page.LeadDetail;
         Test.setCurrentPage(ref1);
         ref1.getParameters().put('id',TestLead1.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(TestLead1);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = true;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = '';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No Send to empower Unlock HLR Lead Id' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
    }
        
    static testmethod void test_Lead_Extension2(){
        Lead TestLead2 = new Lead();
        TestLead2.Channel_Sources__c = 'Bank';
        TestLead2.Channel_Values__c = 'RB Portal';
        TestLead2.FirstName = 'ABCD';
        TestLead2.Status = 'Active';
        TestLead2.VFUpdate__c = 'Yes';
        TestLead2.New_to_Active__c = true;
        TestLead2.Is_Sofi_Lead__c = true;
        TestLead2.My_Lead__c = true;
        TestLead2.Transfer_To_HLR__c = false;
        TestLead2.My_Lead_to_Sofi__c = true;
        TestLead2.Empower_Lead_ID__c = '';
        TestLead2.Property_State__c = 'TX';
        TestLead2.LastName = 'ABCD';
        TestLead2.Company = 'ABCD';
        TestLead2.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send to empower Unlock HLR Lead Id' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead2;
        
        TestLead2.Channel_Sources__c = 'Direct 360';
        TestLead2.Channel_Values__c = 'Inbound';
        update TestLead2;
        
         PageReference ref2= page.LeadDetail;
         Test.setCurrentPage(ref2);
         ref2.getParameters().put('id',TestLead2.id);
         ApexPages.StandardController sc3 = new ApexPages.standardController(TestLead2);
         LeadExtension Cntlr3 = new LeadExtension(sc3);
         Cntlr3.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = true;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = false;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = '';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'MC_Send_to_empower_when_HLR_true' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
  
    }
        
    static testmethod void test_Lead_Extension3(){
        Lead TestLead3 = new Lead();
        TestLead3.Channel_Sources__c = 'Bank';
        TestLead3.Channel_Values__c = 'RB Portal';
        TestLead3.FirstName = 'ABCD';
        TestLead3.Status = 'New - Not Opened';
        TestLead3.VFUpdate__c = 'Yes';
        TestLead3.New_to_Active__c = true;
        TestLead3.Is_Sofi_Lead__c = false;
        TestLead3.My_Lead__c = true;
        TestLead3.Transfer_To_HLR__c = false;
        TestLead3.My_Lead_to_Sofi__c = false;
        TestLead3.Empower_Lead_ID__c = 'D101010';
        TestLead3.Property_State__c = 'TX';
        TestLead3.LastName = 'ABCD';
        TestLead3.Company = 'ABCD';
        TestLead3.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send to empower1' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead3;
        
        TestLead3.Channel_Sources__c = 'Direct 360';
        TestLead3.Channel_Values__c = 'Inbound';
        update TestLead3;
        
         PageReference ref3= page.LeadDetail;
         Test.setCurrentPage(ref3);
         ref3.getParameters().put('id',TestLead3.id);
         ApexPages.StandardController sc4 = new ApexPages.standardController(TestLead3);
         LeadExtension Cntlr4 = new LeadExtension(sc4);
         Cntlr4.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'New - Not Opened';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = false;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = false;
        TestLeadN.My_Lead_to_Sofi__c = false;
        TestLeadN.Empower_Lead_ID__c = 'D101011';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower1' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
       
    }
    
    static testmethod void test_Lead_Extension4(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'New - Not Opened';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = true;
        TestLead4.My_Lead__c = true;
        TestLead4.Transfer_To_HLR__c = true;
        TestLead4.My_Lead_to_Sofi__c = true;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
         //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'New - Not Opened';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = true;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No send to empower in My Sofi Leads' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension5(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = false;
        TestLead4.My_Lead__c = false;
        TestLead4.Transfer_To_HLR__c = true;
        TestLead4.My_Lead_to_Sofi__c = true;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = false;
        TestLeadN.My_Lead__c = false;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No send to empower in My Sofi Leads' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension6(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = true;
        TestLead4.My_Lead__c = false;
        TestLead4.Transfer_To_HLR__c = true;
        TestLead4.My_Lead_to_Sofi__c = true;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = true;
        TestLeadN.My_Lead__c = false;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension7(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = false;
        TestLead4.My_Lead__c = true;
        TestLead4.Transfer_To_HLR__c = true;
        TestLead4.My_Lead_to_Sofi__c = true;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = false;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = true;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No Send To Empower for My Sofi leads with HLR ID Unlocked' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension8(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = false;
        TestLead4.My_Lead__c = true;
        TestLead4.Transfer_To_HLR__c = false;
        TestLead4.My_Lead_to_Sofi__c = true;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No Send to empower2' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = false;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = false;
        TestLeadN.My_Lead_to_Sofi__c = true;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No_Send_to_empower2' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension9(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = false;
        TestLead4.My_Lead__c = true;
        TestLead4.Transfer_To_HLR__c = false;
        TestLead4.My_Lead_to_Sofi__c = false;
        TestLead4.Empower_Lead_ID__c = 'D101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'RB No send to empower in  My Sofi Leads without HLR' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
        //Negative TestLead
        Lead TestLeadN = new Lead();
        TestLeadN.Channel_Sources__c = 'Bank';
        TestLeadN.Channel_Values__c = 'Inbound';
        TestLeadN.FirstName = 'ABCD';
        TestLeadN.Status = 'Active';
        TestLeadN.VFUpdate__c = 'Yes';
        TestLeadN.New_to_Active__c = true;
        TestLeadN.Is_Sofi_Lead__c = false;
        TestLeadN.My_Lead__c = true;
        TestLeadN.Transfer_To_HLR__c = false;
        TestLeadN.My_Lead_to_Sofi__c = false;
        TestLeadN.Empower_Lead_ID__c = 'D101012';
        TestLeadN.Property_State__c = 'TX';
        TestLeadN.LastName = 'ABCD';
        TestLeadN.Company = 'ABCD';
        TestLeadN.RecordTypeId = [select Id from RecordType where Name Like: 'No send to empower in My Sofi Leads without HLR' and SobjectType = 'Lead' limit 1].Id;
        insert TestLeadN;
        
        TestLeadN.Channel_Sources__c = 'RB Portal';
        TestLeadN.Channel_Values__c = 'Inbound';
        update TestLeadN;
        
        PageReference refN= page.LeadDetail;
         Test.setCurrentPage(refN);
         refN.getParameters().put('id',TestLeadN.id);
         ApexPages.StandardController sc1N = new ApexPages.standardController(TestLeadN);
         LeadExtension Cntlr1N = new LeadExtension(sc1N);
         Cntlr1N.init();
        
    }
    
    static testmethod void test_Lead_Extension10(){
        Lead TestLead4 = new Lead();
        TestLead4.Channel_Sources__c = 'Bank';
        TestLead4.Channel_Values__c = 'RB Portal';
        TestLead4.FirstName = 'ABCD';
        //TestLead4.Status = 'Active';
        TestLead4.VFUpdate__c = 'Yes';
        TestLead4.New_to_Active__c = true;
        TestLead4.Is_Sofi_Lead__c = false;
        TestLead4.My_Lead__c = true;
        TestLead4.Transfer_To_HLR__c = false;
        TestLead4.My_Lead_to_Sofi__c = false;
        TestLead4.Empower_Lead_ID__c = 'E101011';
        TestLead4.Property_State__c = 'TX';
        TestLead4.LastName = 'ABCD';
        TestLead4.Company = 'ABCD';
        TestLead4.RecordTypeId = [select Id from RecordType where Name Like: 'For_My_loans' and SobjectType = 'Lead' limit 1].Id;
        insert TestLead4;
        
        TestLead4.Channel_Sources__c = 'Direct 360';
        TestLead4.Channel_Values__c = 'Inbound';
        update TestLead4;
        
         PageReference ref4= page.LeadDetail;
         Test.setCurrentPage(ref4);
         ref4.getParameters().put('id',TestLead4.id);
         ApexPages.StandardController sc5 = new ApexPages.standardController(TestLead4);
         LeadExtension Cntlr5 = new LeadExtension(sc5);
         Cntlr5.init();
        
    }*/
    
}