jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BorrowersHouse__c</fullName>
        <label>Borrowers House#</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Apt__c</fullName>
        <label>Borrowers Apt #</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_County__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_State__c</fullName>
        <description>This is to specify borrower’s State.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_Borrower_Current_Address_to_Subject__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Will copy the Borrower address to Subject Address

Wipro Work</description>
        <label>Copy Borrower Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_Address_1__c</fullName>
        <description>This is to specify the first line of property address.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Address_2__c</fullName>
        <description>This is to specify the second line of property address.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Apt__c</fullName>
        <description>Wipro Work</description>
        <label>Property Apt#</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_City__c</fullName>
        <description>This is to specify property city.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Country__c</fullName>
        <description>Wipro Work</description>
        <label>Property Country</label>
        <length>35</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_County__c</fullName>
        <description>This is to specify Property County.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_House__c</fullName>
        <label>Property House#</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Zip_Postal_Code__c</fullName>
        <description>This is to specify property zip.</description>
        <inlineHelpText>This is subject property address.</inlineHelpText>
        <label>Property Zip/ Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CopyAddress_Test.cls
@IsTest 
 public class CopyAddress_Test {
 
 
  static testmethod void CopyAddress_TestMethod() {
      lead l=new lead();
      l.FirstName= 'asda';
      l.LastName = 'asdad';
      l.Company = 'asda';
      l.email='test@test.com';
      l.Copy_Borrower_Current_Address_to_Subject__c = true;
      l.Borrowers_Apt__c = 'ADSA';
      l.BorrowersHouse__c = 'ASDAD';
      l.Borrowers_Address_1__c = 'aSDAD';
      l.Borrowers_Address_2__c = 'ADASD';
      l.Borrowers_City__c = 'ADSA';
      l.Borrowers_State__c = 'aa';
      l.Borrowers_Country__c = 'adasda';
      l.Borrowers_County__c = 'adsa';
      l.Property_State__c = 'AD';
      l.Borrowers_Zip_Postal_Code__c = '45646';
      insert l;
  }
  static testmethod void CopyAddress_TestMethod1() {
      lead l=new lead();
      l.FirstName= 'asda';
      l.LastName = 'asdad';
      l.Company = 'asda';
      l.email='test@test.com';
      l.Copy_Borrower_Current_Address_to_Subject__c = true;
      l.Property_Apt__c = 'ADSA';
      l.Property_House__c = 'ADSA';
      l.Property_Address_1__c = 'ADSA';  
      l.Property_Address_2__c = 'ADSA';
      l.Property_City__c = 'ADSA';
      l.Property_State__c = 'AD';
      l.Property_County__c = 'ADSA';
      l.Property_Country__c = 'ADSA';
      l.Property_Zip_Postal_Code__c = '45544';
      l.Copy_Borrower_Current_Address_to_Subject__c = false;  
      insert l;    
  }
}