jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>BorrowersHouse__c</fullName>
        <label>Borrowers House#</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Apt__c</fullName>
        <label>Borrowers Apt #</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_County__c</fullName>
        <description>This is to specify borrower’s county.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_State__c</fullName>
        <description>This is to specify borrower’s State.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of co-borrower’s address.</description>
        <label>Co-Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Address_2__c</fullName>
        <description>This is to specify the second line of co-borrower’s address.</description>
        <label>Co-Borrowers Address 2</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Apt__c</fullName>
        <label>Co-Borrowers Apt #</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_City__c</fullName>
        <description>This is to specify co-borrower’s city</description>
        <label>Co-Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Country__c</fullName>
        <description>This is to specify co-borrower’s country.</description>
        <label>Co-Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_County__c</fullName>
        <description>This is to specify co-borrower’s county</description>
        <label>Co-Borrowers County</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Home_Phone__c</fullName>
        <description>This is to specify co-borrower’s home phone.</description>
        <label>Co-Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_House__c</fullName>
        <label>Co-Borrowers House#</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_State__c</fullName>
        <description>This is to specify co-borrower’s State.</description>
        <label>Co-Borrowers State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Co_Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify co-borrower’s zip.</description>
        <label>Co-Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copy_Borrower_Current_Address__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrower Current Address</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Copy_Borrowers_Home_Phone__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Copy Borrowers Home Phone</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <description>The leads can be English or Spanish leads. This field will be used to specify if the lead is English or Spanish.</description>
        <label>Language</label>
        <picklist>
            <picklistValues>
                <fullName>English</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Spanish</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <description>This is used to capture the time zone of the customer</description>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Notes__c.object
<CustomObject>
    <description>Sprint 3</description>
    <label>Note</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Notes Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/TestTriggerUpdateAddressAndPhoneNumber.cls
@isTest(SeeAllData=true)

public class TestTriggerUpdateAddressAndPhoneNumber {
/*

 static testMethod void insertTestLeads() {
 
 // INSERTING A NEW RECORD.
    Lead l=new Lead();
    l.Status='New';
    l.Language__c='English';
    l.Applicant_Type__c = 'Individual';
    l.FirstName = 'TestTrigger';
    l.LastName = 'Yarlagadda';
    l.Time_Zone__c = 'EST';
    l.Borrowers_Current_Residence__c = 'Own';
    l.Company = 'N/A';
    l.Occupancy_Code__c = 'Owner Occupied';
    l.Notes__c = 'Test Notes';
    l.Borrowers_Home_Phone__c = '(504) 213-5698';
    l.BorrowersHouse__c = '8274';
    l.Borrowers_Apt__c = '17-12-45';
    l.Borrowers_Address_1__c = '7933';
    l.Borrowers_Address_2__c = 'Preston Road';
    l.Borrowers_Zip_Postal_Code__c = '75024';
    l.Borrowers_City__c = 'Plano';
    l.Borrowers_State__c = 'TX';
    l.Property_State__c = 'te';  // added by wipro technologies - Yunus H
    l.Borrowers_County__c = 'Collin';
    l.Borrowers_Country__c = 'USA';
    l.Copy_Borrowers_Home_Phone__c = true;
    l.Copy_Borrower_Current_Address__c = true;
     test.starttest();
        insert l;
   test.stoptest();   
   
   //Checking if Borrower and Co- borrowers address is same    
    Lead testLead = [select id,Borrowers_Home_Phone__c,BorrowersHouse__c,Borrowers_Apt__c,Borrowers_Address_1__c,Borrowers_Address_2__c,
                     Borrowers_Zip_Postal_Code__c,Borrowers_City__c,Borrowers_State__c,Borrowers_County__c,Borrowers_Country__c,
                     Co_Borrowers_Home_Phone__c,Co_Borrowers_House__c,Co_Borrowers_Apt__c,Co_Borrowers_Address_1__c,Co_Borrowers_Address_2__c,
                     Co_Borrowers_Zip_Postal_Code__c,Co_Borrowers_City__c,Co_Borrowers_State__c,Co_Borrowers_County__c,Co_Borrowers_Country__c
                     from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda' ];
    
    System.assertEquals(testLead.Borrowers_Home_Phone__c, testLead.Co_Borrowers_Home_Phone__c);
    System.assertEquals(testLead.BorrowersHouse__c, testLead.Co_Borrowers_House__c);
    System.assertEquals(testLead.Borrowers_Apt__c, testLead.Co_Borrowers_Apt__c);
    System.assertEquals(testLead.Borrowers_Address_1__c, testLead.Co_Borrowers_Address_1__c);
    System.assertEquals(testLead.Borrowers_Address_2__c, testLead.Co_Borrowers_Address_2__c);
    System.assertEquals(testLead.Borrowers_Zip_Postal_Code__c, testLead.Co_Borrowers_Zip_Postal_Code__c);
    System.assertEquals(testLead.Borrowers_City__c, testLead.Co_Borrowers_City__c);
    System.assertEquals(testLead.Borrowers_State__c, testLead.Co_Borrowers_State__c);
    System.assertEquals(testLead.Borrowers_County__c, testLead.Co_Borrowers_County__c);
    System.assertEquals(testLead.Borrowers_Country__c, testLead.Co_Borrowers_Country__c);
    
     //Checking the conditions in trigger loops
    Lead testLead3= [select Co_Borrowers_Home_Phone__c,Co_Borrowers_House__c, Co_Borrowers_Apt__c,Co_Borrowers_Address_1__c ,
                     Co_Borrowers_Address_2__c,Co_Borrowers_Zip_Postal_Code__c,Co_Borrowers_City__c,Co_Borrowers_State__c,
                     Co_Borrowers_County__c,Co_Borrowers_Country__c  from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
    
    testLead3.Co_Borrowers_Home_Phone__c = null;
    testLead3.Co_Borrowers_House__c = null;
    testLead3.Co_Borrowers_Apt__c = null;
    testLead3.Co_Borrowers_Address_1__c = null;
    testLead3.Co_Borrowers_Address_2__c = null;
    testLead3.Co_Borrowers_Zip_Postal_Code__c =null;
    testLead3.Co_Borrowers_City__c = null;
    testLead3.Co_Borrowers_State__c = null;
    testLead3.Co_Borrowers_County__c = null;
    testLead3.Co_Borrowers_Country__c = null;    
    
    update testLead3;
    
     Lead testLead4 = [select Copy_Borrowers_Home_Phone__c,Copy_Borrower_Current_Address__c
                      from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
                      
    System.assertEquals(testLead4.Copy_Borrowers_Home_Phone__c, False);
    System.assertEquals(testLead4.Copy_Borrower_Current_Address__c, False);            
    
     //Checking the conditions in trigger loops
     Lead testLead5= [select Co_Borrowers_Home_Phone__c,Co_Borrowers_House__c, Co_Borrowers_Apt__c,Co_Borrowers_Address_1__c ,
                     Co_Borrowers_Address_2__c,Co_Borrowers_Zip_Postal_Code__c,Co_Borrowers_City__c,Co_Borrowers_State__c,
                     Co_Borrowers_County__c,Co_Borrowers_Country__c  from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
    
    testLead5.Co_Borrowers_Home_Phone__c ='(504) 213-5698';
    testLead5.Co_Borrowers_House__c = '8274';
    testLead5.Co_Borrowers_Apt__c = '17-12-45';
    testLead5.Co_Borrowers_Address_1__c = '7933';
    testLead5.Co_Borrowers_Address_2__c = 'Preston Road';
    testLead5.Co_Borrowers_Zip_Postal_Code__c = '75024';
    testLead5.Co_Borrowers_City__c = 'Plano';
    testLead5.Co_Borrowers_State__c = 'TX';
    testLead5.Co_Borrowers_County__c = 'Collin';
    testLead5.Co_Borrowers_Country__c = 'USA';    
    
    update testLead5;         
    
     Lead testLead6 = [select Copy_Borrowers_Home_Phone__c,Copy_Borrower_Current_Address__c
                      from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
                      
    System.assertEquals(testLead6.Copy_Borrowers_Home_Phone__c, False);
    System.assertEquals(testLead6.Copy_Borrower_Current_Address__c, False);         
    
    Lead testLead1= [select Co_Borrowers_Home_Phone__c,Co_Borrowers_House__c 
                     from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
    
    testLead1.Co_Borrowers_Home_Phone__c = '(765) 213-6239';
    testLead1.Co_Borrowers_House__c = '18600';
    
    update testLead1;
    
    //Checking the conditions in trigger loops
    Lead testLead2 = [select Co_Borrowers_Home_Phone__c,Co_Borrowers_House__c,Borrowers_Home_Phone__c,
                       BorrowersHouse__c,Copy_Borrowers_Home_Phone__c,Copy_Borrower_Current_Address__c
                      from Lead where FirstName = 'TestTrigger'and LastName = 'Yarlagadda'];
                      
    System.assertEquals(testLead2.Copy_Borrowers_Home_Phone__c, False);
    System.assertEquals(testLead2.Copy_Borrower_Current_Address__c, False);
    System.assertEquals(testLead2.Co_Borrowers_Home_Phone__c, '(765) 213-6239');
    System.assertEquals(testLead2.Co_Borrowers_House__c, '18600');
    System.assertEquals(testLead2.Borrowers_Home_Phone__c, '(504) 213-5698');
    System.assertEquals(testLead2.BorrowersHouse__c, '8274');               
   }
  */     
}