jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower. In this phase, this lead number will be entered manually in Sales Force. This is both unique (the letters “ABC” are treated differently as “abc”) and External ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Source Lead Number from Empower</inlineHelpText>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Salesforce_Lead_Number__c</fullName>
        <displayFormat>L{000000000}</displayFormat>
        <inlineHelpText>This is a auto generated number for each lead in salesforce</inlineHelpText>
        <label>Salesforce Lead Number</label>
        <type>AutoNumber</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/WebSerLeadStatus.cls
Global class WebSerLeadStatus{
    public class applicationException extends Exception {}
    Webservice Static Boolean updatelead(UpdateLoanStatus vloanLead) {
        
        try{
            Lead TmpLead;
            if(vloanLead.EmpowerID != null){
                TmpLead = [select status,Empower_Lead_ID__c,Salesforce_Lead_Number__c from Lead where Empower_Lead_ID__c =: vloanLead.EmpowerID];
            }
            if(TmpLead != null){
                TmpLead.status = vloanLead.LeadStatus;
                update TmpLead;
                return true;
            }
            else
            {
               throw new applicationException('Invalid Empower ID');
             //  return false;
              
            }   
        }catch(Exception e){
                 return false;
        }
    }


    Global class UpdateLoanStatus{
         webservice String EmpowerID;
         webservice string LeadStatus;
     }

}