jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Notes_Type__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <recordTypes>
        <fullName>Prequal</fullName>
        <active>true</active>
        <businessProcess>Standard Lead Process</businessProcess>
        <description>Standard Record Type for users creating leads and for leads that haven&apos;t been converted</description>
        <label>Prequal</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Notes__c.object
<CustomObject>
    <description>Sprint 3</description>
    <fields>
        <fullName>Comments_List__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <description>sprint 3
Wipro Technologies ltd</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>sprint 3
Wipro Technologies ltd</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Notes</relationshipLabel>
        <relationshipName>Notes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Note</label>
    <nameField>
        <displayFormat>NI-{00000}</displayFormat>
        <label>Notes Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/Notes.cls
/*
Name: CO_ContactManagement_CL
Author: Leena N
Description: This Class is used for creating a new note on lead creation and Notes Updation.
Last modified by: Leena N
*/
public class Notes{
    public void createNotes(List<Lead> New_Leads,list<Lead> Old_Leads){
        Notes__c NewNote1;
        user CreatedbyName ;
        Recordtype NotesRecordtype =  [select Id,name  from RecordType where Name = 'Prequal' and SobjectType = 'Lead' limit 1];
        
        List<Notes__c> insertNotes = new List<Notes__c>();
        List<Lead> UpdateLeadN = new List<Lead>();
        for(integer i = 0 ; i< New_Leads.size(); i++){                           
            if((New_Leads[i].Notes__c != null || New_Leads[i].Notes__c != '' || New_Leads[i].Notes_Type__c != null) &&(New_Leads[i].Notes_Type__c != Old_Leads[i].Notes_Type__c || New_Leads[i].Notes__c !=  Old_Leads[i].Notes__c) ){
                NewNote1 = new Notes__c(
                Lead__c = New_Leads[i].id,               
                Comments__c = New_Leads[i].Notes__c,
                Comments_List__c = New_Leads[i].Notes_Type__c                                    
                );   
                insertNotes.add(NewNote1); 
            } 
        }
        if(insertNotes.size()>0)
            insert insertNotes;           
    }
    public void createInsertNotes(List<Lead> New_Leads){
        Notes__c NewNote1;
        user CreatedbyName ;
        Recordtype NotesRecordtype =  [select Id,name  from RecordType where Name = 'Prequal' and SobjectType = 'Lead' limit 1];       
        List<Notes__c> insertNotes = new List<Notes__c>();
        for(Lead NotesLead : New_Leads){ 
            if((NotesLead.Notes__c != null || NotesLead.Notes__c != '') && NotesLead.Notes_Type__c != null ){
                NewNote1 = new Notes__c(
                Lead__c = NotesLead.id,               
                Comments__c = NotesLead.Notes__c,
                Comments_List__c = NotesLead.Notes_Type__c                                    
                );   
                insertNotes.add(NewNote1);
            }                                                       
        } 
        if(insertNotes.size()>0)
            Insert insertNotes;             
    }
}