jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <description>This is to specify the loan type of the lead.</description>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <description>This is to specify the property type of the lead.</description>
        <label>Property Type</label>
        <picklist>
            <picklistValues>
                <fullName>SFR Detached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SFR Attached</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Low-Rise (1-4)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Rise (5-8)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High-Rise (9+)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Co-op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PUD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Townhome</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2 Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3 Unit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4 Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value_of_Home__c</fullName>
        <description>This is to specify the value of home in dollars.</description>
        <label>Estimated property value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Round_robin_status__c</fullName>
        <label>Round Robin status</label>
        <picklist>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round_robin_time__c</fullName>
        <inlineHelpText>Time in Mins</inlineHelpText>
        <label>Round Robin Wait time</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>RRB Queue Matrix</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Member__c.object
<CustomObject>
    <fields>
        <fullName>Queue_member_proficiency__c</fullName>
        <label>Queue member proficiency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RRB_Queue_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRB Queue Matrix</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>RRB Queue Members</relationshipLabel>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RRB Queue Member</label>
    <nameField>
        <label>RRB Queue Members  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlimited_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlimited Leads</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/SchedulerClass_Test.cls
@isTest
public class SchedulerClass_Test{
Static TestMethod Void Test_SchedulerClass_Test(){
    
Group q = new Group();
q.Name = 'South-Central – Purchase';
q.type = 'Queue';
insert q;
QueueSobject testSQueue = new QueueSObject(QueueId = q.Id, SobjectType = 'Lead');

    System.runAs(new User(Id = UserInfo.getUserId())) {   
    insert testSQueue;
    }
    
User u = [Select id,name,OOO__c,Lead_limit__c,Count__c,Last_assigned__c from user where id =: userInfo.getUserid() limit 1];

RRB_Queue_Matrix__c testQueue = new RRB_Queue_Matrix__c();
testQueue.name = 'South-Central – Purchase';
testQueue.Round_robin_status__c = 'W';
testQueue.Round_robin_time__c = 0; 
insert testQueue ;

RRB_Queue_Member__c testMember1 = new RRB_Queue_Member__c();
testMember1.name = u.name;
testMember1.Queue_member_proficiency__c =1;
testMember1.RRB_Queue_Matrix__c = testQueue.id;
testMember1.user__c = u.id;
insert testMember1;

testMember1 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember1.id];
system.debug('***********memberQueue'+testMember1.RRB_Queue_Matrix__r.name);
system.debug('***********memberQueue'+testMember1.user__r.name);

RRB_Queue_Member__c testMember2 = new RRB_Queue_Member__c();
testMember2.name = u.name;
testMember2.Queue_member_proficiency__c =2;
testMember2.RRB_Queue_Matrix__c = testQueue.id;
testMember2.user__c = u.id;
insert testMember2;

testMember2 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember2.id];
system.debug('***********member2Queue'+testMember2.RRB_Queue_Matrix__r.name);
system.debug('***********member2User'+testMember2.user__r.name);


SchedulerClass sc = new SchedulerClass();
sc.TestRun();

ResetDailyCount rdc= new ResetDailyCount();
rdc.reset();

RRB_Queue_Member__c testMember3 = new RRB_Queue_Member__c();
testMember3.name = u.name;
testMember3.Queue_member_proficiency__c =2;
testMember3.RRB_Queue_Matrix__c = testQueue.id;
testMember3.user__c = u.id;
insert testMember3;

testMember3 =  [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
                FROM RRB_Queue_Member__c  WHERE id =: testMember3.id];
system.debug('***********member3Queue'+testMember3.RRB_Queue_Matrix__r.name);
system.debug('***********member3User'+testMember3.user__r.name);

SchedulerClass sc1 = new SchedulerClass();
sc1.TestRun();

u.unlimited_leads__c = true;
update u;

rdc.reset();

u.Lead_limit__c = null;
update u;  
rdc.reset(); 
    
Lead l44 = new lead(ownerid = q.id);
l44.Channel__c = 'Centralized Retail';
l44.Channel_Sources__c = 'Bank';
l44.Channel_Values__c = 'RB Portal';
l44.FirstName='test';
l44.LastName= 'Lead' ;
l44.Email='test@test.com';
l44.Borrowers_Current_Residence__c='Own';
l44.Company='NA';
l44.Property_State__c='CA';
l44.Loan_Type__c='Conventional';
l44.Occupancy_Code__c='Owner Occupied';
l44.Property_Type__c='SFR Detached';
l44.Value_of_Home__c=300000;
l44.loan_Purpose__c='Purchase';
l44.Requested_Loan_Amount__c=100000;
l44.Department__c ='South-Central';
//l3.ownerid = q.id;
l44.Is_assigned_already__c = false;
insert l44;
    
    
    
u.ooo__c = false;
update u;
testQueue.Current_queue_proficiency_level__c = 2;
testQueue.Next_assigned_user__c = [Select id,name from user where id =: userInfo.getUserid() limit 1].name;    
update testQueue;
RoundRobinScheduler rrc5 = new RoundRobinScheduler();
rrc5.testMethodRun();
    
}
}