jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Mobile_Phone__c</fullName>
        <description>This is to specify borrower’s mobile phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower. In this phase, this lead number will be entered manually in Sales Force. This is both unique (the letters “ABC” are treated differently as “abc”) and External ID.</description>
        <externalId>true</externalId>
        <inlineHelpText>Source Lead Number from Empower</inlineHelpText>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Is_Sofi_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Sofi Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>My_Lead_to_Sofi__c</fullName>
        <defaultValue>false</defaultValue>
        <label>My Lead to Sofi</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes_Type__c</fullName>
        <label>Notes Type</label>
        <picklist>
            <picklistValues>
                <fullName>Called Home, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Home, No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Left Message – No Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell, Made Contact – Follow Up</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Called Cell – No Answer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance Offer Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Prequal Letter Sent (Purchase Offer Made)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – Moved to LOS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted – No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to queue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead - assigned to user</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transfer_To_HLR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Transfer To HLR</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/LeadExtensiontest1.cls
@istest
public with sharing class LeadExtensiontest1 {

 static testmethod void LeadExtensiontest (){
 
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D101010';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.Transfer_To_HLR__c = true;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead__c = false;
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;



        //lead testlead1 = [Select id,name,recordtypeId,status,Empower_Lead_ID__c from lead where status =:'New' and Empower_Lead_ID__c = null limit 1];    
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        /* ref.getParameters().put('id',testlead1.id);
         ApexPages.StandardController sc = new ApexPages.standardController(testlead1);
         LeadExtension Cntlr = new LeadExtension(sc);
         Cntlr.init();*/
          
        // lead testlead2 =[Select id,name,recordtypeId,status,Empower_Lead_ID__c from lead where status =:'New' and Empower_Lead_ID__c = null and Transfer_To_HLR__c =:true limit 1] ;
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.init();
         
      //   lead testlead3 =[Select id,name,recordtypeId,status,Empower_Lead_ID__c where status =:'New' ];
         /*testlead.Is_Sofi_Lead__c = false;
          testlead.My_Lead__c = false;
          update testlead;
          Cntlr = new LeadExtension(sc);
          Cntlr.init();
          

         testlead.Is_Sofi_Lead__c = false ;
         testlead.My_Lead__c = true;
          update testlead;
          Cntlr = new LeadExtension(sc);
          Cntlr.init();


          testlead.Transfer_To_HLR__c = false ;
          testlead.My_Lead_to_Sofi__c = true;
          update testlead;
          Cntlr = new LeadExtension(sc);
          Cntlr.init();


          testlead.My_Lead_to_Sofi__c = false;
          update testlead;
          Cntlr = new LeadExtension(sc);
          Cntlr.init();*/
        
                  
                   
          
         }
 static testmethod void LeadExtensiontest1 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D101010';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead__c = false;
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;

     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr = new LeadExtension(sc2);
         Cntlr.init();
         }
 static testmethod void LeadExtensiontest2 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D101010';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = false;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;

     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr = new LeadExtension(sc2);
         Cntlr.init();
         }
 static testmethod void LeadExtensiontest3 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = '';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = false;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c ='RB Portal';
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Channel__c = 'Centralized Retail';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;

     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr = new LeadExtension(sc2);
         Cntlr.init();
         }
 static testmethod void LeadExtensiontest4 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D101010';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
        /*testlead.My_Lead__c = false;
         testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c ='RB Portal';
         testlead.Channel__c = 'Centralized Retail';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr = new LeadExtension(sc2);
         Cntlr.init();
         }
 static testmethod void LeadExtensiontest5 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = '';
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c ='RB Portal';
         testlead.Transfer_To_HLR__c = true;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Is_Sofi_Lead__c = false;
         testlead.My_Lead__c = false;
         testlead.Channel__c = 'Centralized Retail';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;

        Lead testlead1 = new Lead();
         testlead1.status = 'New - Not Opened';
         testlead1.firstname = 'testfirst';
         testlead1.lastname = 'testlast';
         testlead1.Company = 'Test';
         testlead1.Empower_Lead_ID__c = '';
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead1.Channel_Sources__c = 'Bank';
         testlead1.Channel_Values__c ='RB Portal';
         testlead1.Transfer_To_HLR__c = false;
         /*testlead1.Borrowers_Current_Residence__c = 'test';
         testlead1.Is_Sofi_Lead__c = false;
         testlead1.My_Lead__c = false;
         testlead1.Channel__c = 'Centralized Retail';
         testlead1.Occupancy_Code__c = 'Second Home';
         testlead1.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead1.My_Lead_to_Sofi__c = true;*/
         insert testlead1;
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead1.id);
         ApexPages.StandardController sc = new ApexPages.standardController(testlead1);
         LeadExtension Cntlr = new LeadExtension(sc);
         Cntlr.init();
     
         /*PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);*/
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr1 = new LeadExtension(sc2);
         Cntlr1.init();
}

 static testmethod void LeadExtensiontest6 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D101010';
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c ='RB Portal';
         testlead.Transfer_To_HLR__c = false;
         testlead.Is_Sofi_Lead__c = false;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.My_Lead__c = false;
         testlead.Channel__c = 'Centralized Retail';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;

        Lead testlead1 = new Lead();
         testlead1.status = 'New - Not Opened';
         testlead1.firstname = 'testfirst';
         testlead1.lastname = 'testlast';
         testlead1.Company = 'Test';
         testlead1.Empower_Lead_ID__c = 'D1010101';
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead1.Channel_Sources__c = 'Bank';
         testlead1.Channel_Values__c ='RB Portal';
         testlead1.Is_Sofi_Lead__c = true;
         /*testlead1.Borrowers_Current_Residence__c = 'test';
         testlead1.Transfer_To_HLR__c = false;
         testlead1.My_Lead__c = false;
         testlead1.Channel__c = 'Centralized Retail';
         testlead1.Occupancy_Code__c = 'Second Home';
         testlead1.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead1.My_Lead_to_Sofi__c = true;*/
         insert testlead1;

     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
         ref.getParameters().put('id',testlead1.id);
         ApexPages.StandardController sc = new ApexPages.standardController(testlead1);
         LeadExtension Cntlr1 = new LeadExtension(sc);
         Cntlr1.init();

     
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr = new LeadExtension(sc2);
         Cntlr.init();
}

    static testmethod void LeadExtensiontest7 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.Transfer_To_HLR__c = false;
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         //testlead.Empower_Lead_ID__c = '';
        // testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         //testlead.Transfer_To_HLR__c = true;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead__c = false;
         
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         
      
        
                  
                   
          
         }
         
 
         
        static testmethod void LeadExtensiontest8 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.Transfer_To_HLR__c = false;
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010103';
         testlead.Is_Sofi_Lead__c = True;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         //testlead.Transfer_To_HLR__c = true;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead__c = false;
         
         testlead.My_Lead_to_Sofi__c = true;*/
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         
      
        
                  
                   
          
         }
         
     static testmethod void LeadExtensiontest9 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.Transfer_To_HLR__c = True;
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010403';
         testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         //testlead.Transfer_To_HLR__c = true;
         /*testlead.Borrowers_Current_Residence__c = 'test';
         testlead.Occupancy_Code__c = 'Second Home';
         testlead.Notes_Type__c = 'Called Home, Left Message – No Contact';
         testlead.My_Lead__c = True;
         
         testlead.My_Lead_to_Sofi__c = true;*/
         testlead.My_Lead__c = True;
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         
      
        
                  
                   
          
         } 
         
static testmethod void LeadExtensiontest10 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010103';
         testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = False;
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest11 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010105';
         testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = True;
         //testlead.Transfer_To_HLR__c = True;
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest12 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'E1010105';
         testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = True;
         //testlead.Transfer_To_HLR__c = True;
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest13 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010105';
         testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = false;
         testlead.Channel_Sources__c ='Bank';
         testlead.Channel_Values__c ='RB Portal';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest14 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         //testlead.Empower_Lead_ID__c = 'D1010105';
       //  testlead.Is_Sofi_Lead__c = False;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
       //  testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = false;
        // testlead.My_Lead_to_Sofi__c = false;
         testlead.Channel_Sources__c ='Bank';
         testlead.Channel_Values__c ='RB Portal';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest15 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010105';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
       //  testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = true;
        // testlead.My_Lead_to_Sofi__c = false;
         testlead.Channel_Sources__c ='Bank';
         testlead.Channel_Values__c ='RB Portal';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest16 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010105';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'RB Portal';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest17 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D1010105';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = false;
         testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'Direct 360';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest18 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = '';
        // testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
        // testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = false;
        // testlead.My_Lead_to_Sofi__c = false;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'Inbound';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest19 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D34567';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = true;
         testlead.Transfer_To_HLR__c = true;
         testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'Inbound';
         insert testlead;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }

         static testmethod void LeadExtensiontest20 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst1';
         testlead.lastname = 'testlast1';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D34567';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = false;
       //  testlead.Transfer_To_HLR__c = true;
       //  testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'RB Portal';
         insert testlead;
         testlead.status = 'Active';
         update testlead;

  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
        static testmethod void LeadExtensiontest21 (){
 
         Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst1';
         testlead.lastname = 'testlast1';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D34567';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
       //  testlead.My_Lead__c = true;
       //  testlead.Transfer_To_HLR__c = true;
       //  testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'RB Portal';
         insert testlead;
          testlead.status = 'New - Not Opened';
         update testlead;

  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest22 (){
 
         Lead TestLead = new Lead();
         testlead.status = 'New - Not Opened';
         testlead.firstname = 'testfirst1';
         testlead.lastname = 'testlast1';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D34567';
         testlead.Is_Sofi_Lead__c = true;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
       //  testlead.My_Lead__c = true;
       //  testlead.Transfer_To_HLR__c = true;
       //  testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'Inbound';
         insert testlead;
          testlead.status = 'New - Not Opened';
         update testlead;

  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         static testmethod void LeadExtensiontest23 (){
         
         Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst1';
         testlead.lastname = 'testlast1';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = 'D34567';
         testlead.Is_Sofi_Lead__c = false;
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         testlead.My_Lead__c = false;
       //  testlead.Transfer_To_HLR__c = true;
       //  testlead.My_Lead_to_Sofi__c = true;
         testlead.Channel_Sources__c = 'Bank';
         testlead.Channel_Values__c = 'Inbound';
         insert testlead;
         testlead.status = 'Active';
         update testlead;

  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
         
         
         static testmethod void LeadExtensiontest24 (){
 
         Lead TestLead1 = new Lead();
         testlead1.status = 'Active';
         testlead1.Empower_Lead_ID__c = 'D1010403';
         testlead1.Is_Sofi_Lead__c = false;
         testlead1.My_Lead__c = true;
         testlead1.Transfer_To_HLR__c = true;
         /*testlead.Channel__c = 'Centralized Retail';
         testlead.Channel_Sources__c = 'Bank';*/
         testlead1.firstname = 'testfirst';
         testlead1.lastname = 'testlast';
         testlead1.Company = 'Test';
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         insert testlead1;
         testlead1.status = 'Active';
         update testlead1;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead1.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead1);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead1;
         Cntlr2.init();
         
  
         } 
         
         static testmethod void LeadExtensiontest25 (){
 
         Lead TestLead1 = new Lead();
         testlead1.status = 'Active';
         testlead1.Empower_Lead_ID__c = 'D1010403';
         testlead1.Is_Sofi_Lead__c = false;
         testlead1.My_Lead__c = true;
         testlead1.Transfer_To_HLR__c = true;
         testlead1.Channel_Sources__c = 'Bank';
         testlead1.Channel_Values__c = 'RB Portal';
         testlead1.firstname = 'testfirst';
         testlead1.lastname = 'testlast';
         testlead1.Company = 'Test';
         testlead1.Property_State__c = 'TX';
         testlead1.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         insert testlead1;
         testlead1.status = 'Active';
         update testlead1;


  
     
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead1.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead1);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead1;
         Cntlr2.init();
         
  
         }
         
         static testmethod void LeadExtensiontest26 (){
 
        Lead TestLead = new Lead();
         testlead.status = 'Active';
         testlead.firstname = 'testfirst';
         testlead.lastname = 'testlast';
         testlead.Company = 'Test';
         testlead.Empower_Lead_ID__c = '';
         testlead.Property_State__c = 'TX';
         testlead.Borrowers_Mobile_Phone__c = '(111) 222-3333';
         //testlead.Channel_Sources__c = 'Bank';
         //testlead.Channel_Values__c ='RB Portal';
         testlead.Transfer_To_HLR__c = true;
         insert testlead;
         
         PageReference ref= page.LeadDetail;
         Test.setCurrentPage(ref);
        
          
       
         ref.getParameters().put('id',testlead.id);
         ApexPages.StandardController sc2 = new ApexPages.standardController(testlead);
         LeadExtension Cntlr2 = new LeadExtension(sc2);
         Cntlr2.l=testlead;
         Cntlr2.init();
         }
     
         }