jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>This is used to specify the applicant type</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Address_1__c</fullName>
        <description>This is to specify the first line of borrower’s address.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Address 1</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Apt__c</fullName>
        <label>Borrowers Apt #</label>
        <length>19</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_City__c</fullName>
        <description>This is to specify borrower’s city</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Country__c</fullName>
        <description>This is to specify borrower’s country.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Country</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_Current_Residence__c</fullName>
        <description>This is to specify the borrower’s current residence.</description>
        <label>Borrowers Current Residence</label>
        <picklist>
            <picklistValues>
                <fullName>Own</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Free</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Borrowers_Home_Phone__c</fullName>
        <description>This is to specify borrower’s home phone.</description>
        <inlineHelpText>One of Borrowers Home Phone, Borrowers Work Phone, Borrowers Mobile Phone or  Borrowers Email is required to move the lead to a certain status.</inlineHelpText>
        <label>Borrowers Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Borrowers_Zip_Postal_Code__c</fullName>
        <description>This is to specify borrower’s zip.</description>
        <inlineHelpText>This is borrower’s mailing address.</inlineHelpText>
        <label>Borrowers Zip/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_tax_return_2_years__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business tax return (2 years)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Business_tax_return__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Business tax return</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Cancelled_Checks__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Cancelled Checks</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the high-level category. The second pick list needs to be used to further drill down to channel source.</description>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Inbound Calls</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Assigned Applications</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Outbound Leads</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <description>This is to specify the channel sources from which the lead was generated. This pick list is to specify the low-level category. The values in this pick list will change dynamically based on the value selected in the previous pick list.</description>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Pull Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payoff Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer - RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention- Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is to specify the channel from which the lead was generated.</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Closing_Date__c</fullName>
        <label>Closing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Document_Deadline__c</fullName>
        <label>Document Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>HUD_1_Settlement_Statement__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HUD-1 Settlement Statement</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Intened_use_of_Cash_Out_funds__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Intened use of &quot;Cash Out&quot; funds</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Loan_Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Loan Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_recent_W_2_2_years__c</fullName>
        <defaultValue>false</defaultValue>
        <label>W-2 (2 years)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Most_recent_W_2__c</fullName>
        <defaultValue>false</defaultValue>
        <label>W-2</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>This is to capture notes about the lead.</description>
        <label>Comments</label>
        <length>4000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <description>This is to specify the occupancy type of the lead.</description>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Outstanding_Mortgages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outstanding Mortgages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pay_stub__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pay stub(s)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pension_Annuity_Statements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Pension/Annuity Statements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Personal_tax_return_2_years__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal tax return (2 years)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Personal_tax_return__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Personal tax return</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <description>This is to specify Property State.</description>
        <inlineHelpText>This field is required.</inlineHelpText>
        <label>Property State</label>
        <length>2</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Social_Security_award_letter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Social Security award letter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Stocks_IRA_401k_Statements__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Stocks/IRA/401k Statements</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Time_Zone__c</fullName>
        <description>This is used to capture the time zone of the customer</description>
        <label>Time Zone</label>
        <picklist>
            <picklistValues>
                <fullName>EST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PST</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MST</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>NMLS_ID__c</fullName>
        <label>NMLS ID</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_SendEmail_Test.cls
@isTest
public class CO_SendEmail_Test{
    Static TestMethod Void TestCO_SendEmail(){
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator'];
        User u = new User(alias = 'jsmtih', email='jsmith@acme.com',
                        emailencodingkey='UTF-8', lastname='Smith',firstname='John',
                        languagelocalekey='en_US',
                        localesidkey='en_US', profileid = p.Id,
                        timezonesidkey='America/Los_Angeles',
                        username='jsmith@acme2345.com',isactive=true,street='asds',city='asfd',
                        postalcode='23445',phone='',mobilephone='',fax='',nmls_id__c=65789,state='ka');
        insert u;
         
        System.runAs ( u ) {
        Lead new_ld1 = new Lead();
        new_ld1.Status='New';
        new_ld1.ownerid=u.id;
        new_ld1.Applicant_Type__c='individual';
        new_ld1.Channel__c='Home Equity';
        new_ld1.Channel_Sources__c='Bank';
        new_ld1.Channel_Values__c='NCFR';
        new_ld1.FirstName='ROSY';
        new_ld1.LastName='DANIAL';
        new_ld1.Borrowers_Country__c='Hong Kong';
        new_ld1.Borrowers_City__c='Netherlands';
        new_ld1.Borrowers_Address_1__c='A-12 Lonley Road';
        new_ld1.Time_Zone__c='EST';
        new_ld1.Borrowers_Current_Residence__c='Own';
        new_ld1.Company='XXXX';
        new_ld1.Loan_Approved__c=True;
        new_ld1.Borrowers_Zip_Postal_Code__c='32412';
        new_ld1.Borrowers_Home_Phone__c='(033) 246-3970';
        new_ld1.Occupancy_Code__c='Second Home';
        new_ld1.Notes__c='Tomorrow is Saturday';
        new_ld1.Property_State__c='CA';
        new_ld1.Email='ak@gmail.com';
        new_ld1.Phone='(033) 246-3970';
        new_ld1.Borrowers_Apt__c='Test';
        insert new_ld1;
        
        Folder fdr = [Select id,AccessType,Name,Type,developername from Folder where name='Transactional Emails'];
        EmailTemplate et = new EmailTemplate(markup='<messaging:emailTemplate subject="Loan terms update" recipientType="Lead" replyTo="{!$User.Email}"><messaging:htmlEmailBody ></messaging:htmlEmailBody></messaging:emailTemplate>',name='asdm',TemplateType='Visualforce',Folderid=fdr.id,Developername='newtemplate'); 
        insert et;
        Emailtemplate et1= new Emailtemplate(body='dsfsdf',developername='testolp',subject='test',folderid=fdr.id,templatetype='custom',name='testopli');
        insert et1;
        apexpages.currentpage().getparameters().put('id',new_ld1.id);
        ApexPages.StandardController sc = new ApexPages.standardController(new_ld1);
        CO_SendEmail Cntlr = new CO_SendEmail(sc);
        Cntlr.selectedfoldername=fdr.name;
        Cntlr.SelectedEmailId=et.id;
        Cntlr.Selectedfolderemails();
        Cntlr.Selectedemailmethod();
        Cntlr.getPreview();
        Cntlr.sendmail();
        Cntlr.SelectedEmailId='Weneedinfo';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        Cntlr.SelectedEmailid='NextSteps';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        Cntlr.SelectedEmailid='loanclosing';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        /*Cntlr.SelectedEmailid='';
        Cntlr.Selectedemailmethod();*/
        Cntlr.lea.Closing_Date__c=system.today();
        Cntlr.lea.Document_Deadline__c=system.today();
            
        u.Phone='1234567890';
        u.MobilePhone='1234567890';
        u.Fax='1234567890';
        Cntlr.Urloanclosing();
        Cntlr.weneedinfo();
        Cntlr.NextStepsAfterLoanSubmission();
        Cntlr.lea.pay_stub__c=true;
        Cntlr.lea.Most_recent_W_2__c=true;
        Cntlr.lea.Most_recent_W_2_2_years__c=true;
        Cntlr.lea.Personal_tax_return__c=true;
        Cntlr.lea.Personal_tax_return_2_years__c=true;
        Cntlr.lea.Business_tax_return__c=true;
        Cntlr.lea.Business_tax_return_2_years__c=true;
        Cntlr.lea.Social_Security_award_letter__c=true;
        Cntlr.lea.Pension_Annuity_Statements__c=true;
        Cntlr.lea.Cancelled_checks__c=true;
        Cntlr.lea.Cancelled_checks__c=true;
        Cntlr.lea.Stocks_IRA_401k_Statements__c=true;
        Cntlr.lea.Outstanding_Mortgages__c=true;
        Cntlr.lea.HUD_1_Settlement_Statement__c=true;
        Cntlr.lea.Intened_use_of_Cash_Out_funds__c=true;
        Cntlr.lea.Sales_Contract__c=true;
        Cntlr.lea.Divorce_Separation_decree__c=true;
        Cntlr.lea.Driver_s_License__c=true;
        Cntlr.lea.Homeowner_s_insurance_policy__c=true;
        Cntlr.lea.Homeowner_s_Condo_Association__c=true;
        Cntlr.lea.Documentation_of_credit_dispute__c=true;
        Cntlr.lea.Property_Survey__c=true;
        Cntlr.lea.RESPA_documents__c=true;
        Cntlr.lea.Irrevocable_Trust__c=true;
        Cntlr.lea.Documents_for_Non_US_Citizens__c='sfdfgfh';
        Cntlr.lea.Statement_s_of_debts__c='sffgh';
        Cntlr.lea.Other__c='fdfgth';
        Cntlr.lea.Bank_Statements__c=true;
        Cntlr.SelectedEmailid='NextSteps';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        Cntlr.SelectedEmailId='Weneedinfo';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        Cntlr.lea.Made_Payable_To__c='fhfgjgh';
        Cntlr.SelectedEmailid='loanclosing';
        Cntlr.Selectedemailmethod();
        Cntlr.sendmail();
        Cntlr.Cancel();
        Cntlr.SelectedEmailId=et.id;
        Cntlr.getPreview();
        Cntlr.Selectedfolderemails();
        Cntlr.Selectedemailmethod();
        Cntlr.SelectedEmailid='loanclosing';
        Cntlr.lea.closing_date__c=system.today();
        Cntlr.lea.Closing_Costs__c=545;
        Cntlr.lea.Made_Payable_To__c='dsgfdr';
        Cntlr.sendmail();
        string s='sfsdg';
        blob b=blob.valueof(s);
        Attachment a= new Attachment(name='qqq.pdf', body=b);
        Cntlr.attachments.add(a);
        Cntlr.sendmail();
            
        string k='';
        blob d=blob.valueof(k);
        Attachment c= new Attachment(name='', body=d);
        Cntlr.attachments.add(c);
        Cntlr.sendmail();
        //Cntlr.attachments[0].name='qqq.pdf';
        //Cntrl.attachments[0].body=b;
        
        }
    }
}