jvimalprasathdev/src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Lead_Stage__c</fullName>
        <description>Picklist with three values: My Leads, My Sofi Leads, My Loans, that Lead Status is dependent on.</description>
        <label>Lead Stage</label>
        <picklist>
            <picklistValues>
                <fullName>My Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Sofi Leads</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>My Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <description>This is to specify the loan purpose of the lead. The values in the pick list will change dynamically based on “Loan Type” selection above.</description>
        <label>Loan Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <label>Loan Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Shopping_Stage__c</fullName>
        <label>When do you intend to apply?</label>
        <picklist>
            <picklistValues>
                <fullName>1-2 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-2 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4+ months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <label>Loan Purpose</label>
        <picklist>
            <controllingField>Loan_Type__c</controllingField>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streamline Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRRRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Contacted / Follow Up Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request For Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / No Product Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Went with another Lender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Application Taken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Offer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Offer Not Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Closed/Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Still Deciding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Appointment Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Customer Rate Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Property Type Not Offered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <picklist>
            <picklistValues>
                <fullName>Hot</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Shopping_Stage__c</fullName>
        <label>When do you intend to apply?</label>
        <picklist>
            <picklistValues>
                <fullName>1-2 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 weeks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>1-2 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2-4 months</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4+ months</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/StatusRatingMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Mapping for Rating</description>
    <fields>
        <fullName>Default_Mapping_Fields_Name__c</fullName>
        <inlineHelpText>mapping field = lead/opp field eg: Stage__c=Stagename</inlineHelpText>
        <label>Default Mapping Fields Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Default__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Default</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LoanPurpose__c</fullName>
        <label>Loan Purpose</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <inlineHelpText>Please enter the Semicolon-separated values only. eg Lead;Opportunity</inlineHelpText>
        <label>Object Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_to_Apply__c</fullName>
        <label>Time to Apply</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>StatusRatingMapping</label>
</CustomObject>

jvimalprasathdev/src/classes/UpdateRatings.cls
public with sharing class UpdateRatings {

private static Map<String,String> mappings_Map = new Map<String,String>();
    
    public static void getOppRatings(List<Opportunity> opps){
        init();
        for(Opportunity opp: opps){
            obj = opp;
            initFieldDetails(opp,null);
            updateRating();
            opp.Rating__c = ratingValue;
            ratingValue = null;
            //updateOppRating(opp);
        }
    }
    
    
    public static void getLeadRatings(List<Lead> leads){
        init();
        for(Lead ld: leads){
            obj = ld;
            initFieldDetails(null,ld);
            updateRating();
            ld.Rating = ratingValue;
            ratingValue = null;
        }
    }
    
    private static sObject obj;
    private static String objName;
    private static String loanPurpose;
    private static String status;
    private static String stage;
    private static String timeToApply;
    private static String ratingValue;
    //private static Map<String, StatusRatingMapping__c> cs;
    private static Map<Integer, StatusRatingMapping__c> cs_int;
    private static List<Integer> keys;
    //private static Pattern objectName_p,loanPurpose_p,status_p,stage_p,timeToApply_p;
    
    private static  void init(){
        Map<String, StatusRatingMapping__c> cs = StatusRatingMapping__c.getAll();

        cs_int = new Map<Integer, StatusRatingMapping__c>();
        for(String key : cs.keySet()){
            cs_int.put(Integer.valueOf(key), cs.get(key));
        }
        
        keys = new List<Integer>(cs_int.keySet());
        keys.sort();
        
    }
    private static void initFieldDetails(Opportunity opp, Lead ld){
        
        objName = (ld!=null)? 'Lead':'Opportunity';
        loanPurpose = (ld!=null)? ld.Loan_Purpose__c:opp.Loan_Purpose__c;
        status = (ld!=null)? ld.status:opp.Loan_Status__c;
        stage = (ld!=null)? ld.Lead_Stage__c :opp.StageName;
        timeToApply = (ld!=null)? ld.Shopping_Stage__c:opp.Shopping_Stage__c;
    }
    
    private static void updateRating(){
            
        for(Integer key : keys){
            StatusRatingMapping__c srm = cs_int.get(key);
            if(!srm.Is_Default__c ){
            
            Pattern objectName_p  = Pattern.compile('(?i)' + String.join(new List<String>(srm.Object_Name__c.split(';')),'|'));
            Pattern loanPurpose_p = Pattern.compile('(?i)' + String.join(new List<String>(srm.LoanPurpose__c.split(';')),'|').replace('+','\\+'));
            Pattern status_p = Pattern.compile('(?i)' + String.join(new List<String>(srm.Status__c.split(';')),'|').replace('+','\\+'));
            Pattern stage_p = Pattern.compile('(?i)' + String.join(new List<String>(srm.stage__c.split(';')),'|').replace('+','\\+'));
            Pattern timeToApply_p = Pattern.compile('(?i)' + String.join(new List<String>(srm.Time_To_Apply__c.split(';')),'|').replace('+','\\+'));
               
               if(  
                   objectName_p.matcher(objName).matches() &&
                   ( (srm.LoanPurpose__c.trim()).equalsIgnoreCase('Any')  || loanPurpose_p.matcher(loanPurpose).find() ) &&
                   ( (srm.Status__c.trim()).equalsIgnoreCase('Any') || status_p.matcher(status).matches() ) &&
                   ( (srm.stage__c.trim()).equalsIgnoreCase('Any')  || stage_p.matcher(stage).matches() ) &&
                   ( (srm.Time_to_Apply__c.trim()).equalsIgnoreCase('Any') ||  timeToApply_p.matcher(timeToApply).matches())
                  )
                   
                {
                    
                    ratingValue = srm.Rating__c;
                    break;
                }
                ratingValue = '';
            }
        }
        
        if(ratingValue==''){
            for(Integer key : Keys){
                StatusRatingMapping__c srm = cs_int.get(key);
                Pattern objectName_p  = Pattern.compile('(?i)' + String.join(new List<String>(srm.Object_Name__c.split(';')),'|'));
                
                if(srm.Is_Default__c && objectName_p.matcher(objName).matches()){
                    List<String> fields = srm.Default_Mapping_Fields_Name__c.split(';');
                     String rating = '';
                     for(String fld : fields){
                        String[] str = fld.split('=');
                        
                        Pattern defaultPattern = Pattern.compile('(?i)' + String.join(new List<String>(String.valueOf(srm.get(str[0].trim())).split(';')),'|').replace('+','\\+'));
                        if(!( (String.valueOf(srm.get(str[0].trim()))).equalsIgnoreCase('Any') ||  defaultPattern.matcher(String.valueOf(obj.get(str[1].trim()))).find()   ) ){
                            ratingValue ='';
                            break;
                        }
                        ratingValue = srm.Rating__c;
                     }
                     
                     if(!ratingValue.equalsIgnoreCase('')){
                        break;
                     }
                }
            }
        }   
            
    }
    
    

}