jvimalprasathdev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Applicant_Type__c</fullName>
        <description>Type of applicant</description>
        <label>Applicant Type</label>
        <picklist>
            <picklistValues>
                <fullName>Individual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Married Couple</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Two Individuals (Not Married)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than Two Individuals</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Sources__c</fullName>
        <label>Channel Sources</label>
        <picklist>
            <picklistValues>
                <fullName>Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Campaigns</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Third Parties</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate Table</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid Search</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banner Ad</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct 360</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Campaign</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Referral</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel_Values__c</fullName>
        <label>Channel Values</label>
        <picklist>
            <controllingField>Channel_Sources__c</controllingField>
            <picklistValues>
                <fullName>Bankrate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RB Portal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Google</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mobile</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Yahoo/Bing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Outbound Campaign Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Mail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct Email</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cross-sell Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Share Builder Triggers</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CapitalOne.com Web</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attorney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Realtors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Builders</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financial Advisors</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Title Company</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CPA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Employee Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention - Current Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Warm Transfer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retention - Previous Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loans Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NCFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail MC Website</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Web</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <description>This is the channel from which the lead was generated</description>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Centralized Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Distributed Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Retail</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Neighborhood Lending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower.  This is both Unique and an External ID</description>
        <externalId>true</externalId>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Loan_Status__c</fullName>
        <label>Status</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Contacted / Follow Up Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Request For Prequal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / No Product Available</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / No Longer Interested</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Went with another Lender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Application Taken</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Offer Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Offer Not Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Closed/Funded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Withdrawn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Still Deciding</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Appointment Made</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Customer Rate Shopping</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contacted / Property Type Not Offered</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Occupancy_Code__c</fullName>
        <label>Occupancy Code</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Second Home</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Requested_Loan_Amount__c</fullName>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/wsLead_Test.cls
@istest(seeAllData = true)
public class wsLead_Test{
    public static testMethod void wsLead_TestMethod(){
    String EmpowerID = '244';
    String OpportunityStatus = 'Acitve 1';
     Opportunity opp = new Opportunity();
     opp.name = 'ABC';
     opp.Channel__c = 'Centralized Retail';
     opp.Channel_Sources__c = 'Web';
     opp.Channel_Values__c = 'Google';
     opp.CloseDate = date.today();
     opp.Applicant_Type__c = 'Individual';
     opp.StageName = 'Prospecting';
     opp.Occupancy_Code__c = 'Owner Occupied';
     opp.Loan_Type__c = 'HE';
     opp.Requested_Loan_Amount__c = 5456;
     opp.Loan_Status__c = 'Active';
     opp.Empower_Lead_ID__c = '2442';
     insert opp;
     
     /*opp.Loan_Status__c = OpportunityStatus;
     opp.Empower_Lead_ID__c = OpportunityStatus;
     update opp;*/
     
     wsLead.UpdateLoanStatus ws = new wsLead.UpdateLoanStatus();
     list<String> res = new list<string>();
     res = wsLead.updateLead(ws);
     ws.OpportunityStatus = 'Active';
     ws.EmpowerID = '2442';
     ws.AppraisedValue=1000;
     ws.ClosingDate=Date.today();
     ws.DisbursementDate=Date.today();
     ws.LoanAmount=100;
     ws.LoanPurpose='testpurpose';
     ws.LoanTerm='15';
     ws.LockExpirationDate=Date.today();
     res = wsLead.updateLead(ws);
     
    }
    
    public static testMethod void wsLead_TestMethod2(){
    String loanId = '2442';
     Opportunity opp = new Opportunity();
     opp.name = 'ABC';
     opp.Channel__c = 'Centralized Retail';
     opp.Channel_Sources__c = 'Web';
     opp.Channel_Values__c = 'Google';
     opp.CloseDate = date.today();
     opp.Applicant_Type__c = 'Individual';
     opp.StageName = 'Prospecting';
     opp.Occupancy_Code__c = 'Owner Occupied';
     opp.Loan_Type__c = 'HE';
     opp.Requested_Loan_Amount__c = 5456;
     opp.Loan_Status__c = 'Active';
     opp.Empower_Lead_ID__c = '2442';
     insert opp;
     
     opp.Empower_Lead_ID__c = loanId;
     update opp;
     
     /*opp.Loan_Status__c = OpportunityStatus;
     opp.Empower_Lead_ID__c = OpportunityStatus;
     update opp;*/
     
     wsLead.UpdateeidField ws = new wsLead.UpdateeidField();
     list<String> res = new list<string>();
     res = wsLead.updateEID(ws);
     ws.OpportunityId = opp.id;
     ws.loanId = '2442';
     //ws.Empower_Lead_ID__c = '2442';
     res = wsLead.updateEID(ws);
     
    }
    
}