jvimalprasathdev/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Empower_Lead_ID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>This is the lead number from Empower.  This is both Unique and an External ID</description>
        <externalId>true</externalId>
        <label>OPUS ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Loan_Purpose__c</fullName>
        <label>Loan Purpose</label>
        <picklist>
            <controllingField>Loan_Type__c</controllingField>
            <picklistValues>
                <fullName>Purchase</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cash-out Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Streamline Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IRRRL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rate &amp; Term Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HEL - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 1st Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HELOC - 2nd Lien</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Loan_Type__c</fullName>
        <label>Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Conventional</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FHA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USDA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Property_State__c</fullName>
        <label>Property State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/WsleadTest.cls
@isTest
public class WsleadTest {
  
  static testMethod void wsleadtest()
  {
  Opportunity op= new opportunity( Name='John Doe',StageName='Offer Not Accepted',CloseDate=system.today(),Empower_Lead_ID__c ='TestEID12334',Property_State__c ='TX',loan_purpose__c ='test',loan_type__c='test');
  insert op;
  

    wslead.UpdateLoanStatus ttf = new  wslead.UpdateLoanStatus();
    wslead.updatelead(ttf);
    ttf.EmpowerID = 'TestEID12334';
    ttf.OpportunityStatus = 'Open';
    wslead.updatelead(ttf);
   

   Opportunity[] opp = [select Empower_Lead_ID__c from Opportunity where Empower_Lead_ID__c = 'TestEID12334'];
   

   string EmpowerID = 'emp123';
   string LeadStatus = 'Open';
   wslead.UpdateLoanStatus led = new wslead.UpdateLoanStatus(); 
  }
  
  
  
  static testMethod void wsleadtest1() {
   Opportunity op2= new opportunity(Name='John Doe',StageName='Offer Not Accepted',CloseDate=system.today(),Empower_Lead_ID__c ='TestEID12334',Property_State__c ='TX',loan_purpose__c ='test',loan_type__c='test');
  insert op2;
  
  wslead.UpdateeidField ttf = new  wslead.UpdateeidField();
    ttf.OpportunityID = 'TestEI';
    wslead.updateEID(ttf);
    ttf.OpportunityID = 'TestEID12334';
    ttf.loanID= '123456789';
    wslead.updateEID(ttf);
}
  
 static testMethod void wsleadtest2() {
  Opportunity op1= new opportunity(Name='John Doe',StageName='Offer Not Accepted',CloseDate=system.today(),Empower_Lead_ID__c ='TestDID12335',Property_State__c ='TX',loan_purpose__c ='test',loan_type__c='test');
  insert op1;
  
    wslead.UpdateeidField ttf = new  wslead.UpdateeidField();
    ttf.OpportunityID ='TestDID12335';
    ttf.loanID='TestEID12335';
    wslead.updateEID(ttf);
    ttf.OpportunityID ='TestEID12334';
    wslead.updateEID(ttf);
 
     
  }
}