jvimalprasathdev/src/objects/Realtor_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <externalId>true</externalId>
        <label>Mailing ZIP/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Realtor__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is the flag that is to say that this does not exist already in the Realtor DB</description>
        <label>New Realtor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Total_no_of_Leads__c</fullName>
        <label>Total no.of Leads</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Realtor Contacts</label>
    <nameField>
        <label>Realtor Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtor Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_SearchRealtorContacts_CL.cls
public with sharing class CO_SearchRealtorContacts_CL {
    public List<Realtor_contacts__c> Realtorcons {get;set;}
    public string zipcode {get;set;}
    public Boolean showmesg {get;set;}
    public Boolean showtable {get;set;}
    public String messg {get;set;}
    List<ContactWrapper> actualContacts = new List<ContactWrapper>();
    
    public CO_SearchRealtorContacts_CL(){
        Realtorcons = new List<Realtor_contacts__c>();
    }
    public void findRealtorCons()
    {        
         Realtorcons = [select id,Name,phone__c,email__c,Mailing_ZIP_Postal_Code__c,createddate,Total_no_of_Leads__c from Realtor_Contacts__c where New_Realtor__c =:true and Mailing_ZIP_Postal_Code__c=:zipcode  order by phone__c,email__c,createddate limit 1000 ];
         if(Realtorcons!=null && Realtorcons.size()>0){                         
             ContactWrappermethod(Realtorcons);
             showtable=true;
             showmesg=false; 
                    
         }else{
             showmesg=true;
             showtable=false;
             messg = 'No records found with given Zip/Postal code';  
              
         }  
    }
    public void ContactWrappermethod(List<Realtor_Contacts__c> Contacts){
        actualContacts = new List<ContactWrapper>();
        for(integer i=0; i<Contacts.size(); i++){
            ContactWrapper wrapclass = new ContactWrapper(Contacts[i]);
            actualContacts.add(wrapclass);
        }
    }
    public class ContactWrapper{
        public string createddate{get; set;}
        public Realtor_Contacts__c Con{get; set;}
        public ContactWrapper(Realtor_Contacts__c conObj){
            createddate=conObj.createddate.format();
            Con=conObj;        
        }
    }
    public List<ContactWrapper> getVFContacts(){
        return actualContacts;
    }
}