jvimalprasathdev/src/objects/Realtor_Contact_Management__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Realtor_Contact_Managemants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Realtor_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Realtor Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Realtor_Contacts__c.Deactivate__c</field>
                <operation>equals</operation>
                <value>False</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Realtor_Contacts__c</referenceTo>
        <relationshipLabel>Realtor Contact Managements</relationshipLabel>
        <relationshipName>Realtor_Contact_Managemants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Realtor Contact Management</label>
    <nameField>
        <displayFormat>RC-{000000}</displayFormat>
        <label>Realtor Contact Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Realtor Contact Managements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/CO_RealtorManagement_CL.cls
public with sharing class CO_RealtorManagement_CL{
    public Realtor_Contact_Management__c RelMgt{set; get;}
    public id LeadId{get; set;}
    
    public CO_RealtorManagement_CL(ApexPages.StandardSetController controller){
        LeadId= system.currentPageReference().getParameters().get('id');        
        RelMgt= new Realtor_Contact_Management__c();
        RelMgt.Lead__c = Leadid;
    }
    public PageReference SaveRelMgt(){
        try{
        if(RelMgt.Realtor_Contact__c!=null){
            insert RelMgt;
         PageReference pr = new PageReference('/' + LeadId);  
         pr.setRedirect(true);  
         return pr;
         }
         else{
              ApexPages.addMessage(new ApexPages.message(ApexPages.severity.FATAL,'Enter Realtor')); 
              return null;
         }
         }
         catch(Exception e){
         }
         return null;
    }
    public PageReference Cancel(){
        return (new pageReference('/' +LeadId));
    }
}