jvimalprasathdev/src/objects/Realtor_Contacts__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Mailing_ZIP_Postal_Code__c</fullName>
        <externalId>true</externalId>
        <label>Mailing ZIP/Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile_Phone__c</fullName>
        <label>Mobile Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>No_of_Leads__c</fullName>
        <label>No.of Leads</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Realtor_Id__c</fullName>
        <description>This stores the Id of the original realtor</description>
        <label>Realtor Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_no_of_Leads__c</fullName>
        <label>Total no.of Leads</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Realtor Contacts</label>
    <nameField>
        <label>Realtor Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realtor Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/Realtor_AI_AU_Test.cls
@isTest(seeAllData = true)
Public Class Realtor_AI_AU_Test{
    Static testmethod void Realtor_AI_AU_Testmethod(){
        Realtor_contacts__c rc1= new Realtor_contacts__c();
        rc1.name='Lee';
        rc1.mailing_zip_postal_code__c='44444';
        rc1.Total_no_of_Leads__c = 0;
        rc1.No_of_Leads__c = null;
        rc1.Realtor_Id__c = null;
        insert rc1;
        
        Realtor_contacts__c rc= new Realtor_contacts__c();
        rc.name='Lee';
        rc.mailing_zip_postal_code__c='44444';
        rc.Total_no_of_Leads__c = 0;
        rc.No_of_Leads__c = null;
        rc.Realtor_Id__c = [select id from Realtor_contacts__c where name like '%Lee%' limit 1].id;
        rc.Phone__c = '1111111111';
        rc.Email__c = 'test@test.com';
        rc.Home_Phone__c = '2222222222';
        rc.Mobile_Phone__c = '3333333333';
        insert rc;
       
        Realtor_contacts__c rc2 =  [select id,Realtor_Id__c from Realtor_contacts__c where name like '%Lee%'limit 1];
        rc2.Realtor_Id__c = null;
        update rc2;
                       
        delete rc1;
        
        CO_SearchRealtorContacts_CL SRC= new CO_SearchRealtorContacts_CL();
        src.zipcode='44444';
        src.findRealtorCons();
        src.getVFContacts();
        src.zipcode='44443';
        src.findRealtorCons();
    }
  
}