jvimalprasathdev/src/objects/RRB_Queue_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Current_queue_proficiency_level__c</fullName>
        <label>Current queue proficiency level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_assigned_user__c</fullName>
        <label>Next assigned user</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Round_robin_status__c</fullName>
        <label>Round Robin status</label>
        <picklist>
            <picklistValues>
                <fullName>W</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Y</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Round_robin_time__c</fullName>
        <inlineHelpText>Time in Mins</inlineHelpText>
        <label>Round Robin Wait time</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>RRB Queue Matrix</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Member__c.object
<CustomObject>
    <fields>
        <fullName>Queue_member_proficiency__c</fullName>
        <label>Queue member proficiency</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RRB_Queue_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRB Queue Matrix</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>RRB Queue Members</relationshipLabel>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RRB Queue Member</label>
    <nameField>
        <label>RRB Queue Members  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Scheduler__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Current_User_ID__c</fullName>
        <label>Current User ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_User_Name__c</fullName>
        <label>Current User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_Limit__c</fullName>
        <label>Lead Limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_User_Id__c</fullName>
        <label>Next User Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Next_User_Name__c</fullName>
        <label>Next User Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue Name</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>Schedulers</relationshipLabel>
        <relationshipName>Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Proficiency_Level__c</fullName>
        <description>To fetch value from Queue Members.</description>
        <label>Current User Proficiency Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scheduler</label>
    <nameField>
        <label>Scheduler Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Last_Assigned__c</fullName>
        <label>Last Assigned</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/SchedulerClass.cls
public class SchedulerClass {


public void TestRun(){

list<scheduler__c> sh = [select id from scheduler__c];
delete sh;

List<RRB_Queue_Matrix__c> listQueues = [SELECT Current_queue_proficiency_level__c,Id,Name,Next_assigned_user__c,Round_robin_status__c,Round_robin_time__c,SystemModstamp FROM RRB_Queue_Matrix__c];

List<RRB_Queue_Member__c> listMem = [SELECT name,Id,Queue_member_proficiency__c,RRB_Queue_Matrix__c,RRB_Queue_Matrix__r.Name,User__c,user__r.id,user__r.name,user__r.OOO__c,user__r.Lead_limit__c,user__r.Count__c,user__r.Last_assigned__c 
FROM RRB_Queue_Member__c  WHERE RRB_Queue_Matrix__c in :listQueues 
ORDER BY RRB_Queue_Matrix__r.Name,Queue_member_proficiency__c,user__r.Last_assigned__c];

Integer memSize = listMem.size();

For(Integer i=0; i<memSize; i++) 
system.debug('*****************listMem'+i+listMem[i].user__r.name+listMem[i].RRB_Queue_Matrix__r.Name);

List<Scheduler__c> sched = new List<Scheduler__c>();

RRB_Queue_Member__c firstmem = listMem[0];


For(Integer i=0; i<memSize-1; i++){
Scheduler__c tempSch =  new Scheduler__c();
system.debug('*****************listMem[i].user__r.name'+i+listMem[i].user__r.name);
system.debug('*****************listMem[i].RRB_Queue_Matrix__c'+i+listMem[i].RRB_Queue_Matrix__c);
system.debug('*****************firstmem.user__r.name'+firstmem.user__r.name);
tempSch.Name = listMem[i].user__r.name;
tempSch.Count__c = 0;
tempSch.Lead_Limit__c = listMem[i].user__r.Lead_limit__c;
tempSch.OOO__c = listMem[i].user__r.OOO__c;
tempSch.Last_Assigned__c = listMem[i].user__r.Last_assigned__c;
tempSch.Queue_Name__c = listMem[i].RRB_Queue_Matrix__c;
tempSch.Current_User_Name__c = listMem[i].user__r.name;
tempSch.Current_User_ID__c = listMem[i].user__r.id;
tempSch.User_Proficiency_Level__c = listMem[i].Queue_member_proficiency__c;

if(listMem[i].Queue_member_proficiency__c == listMem[i+1].Queue_member_proficiency__c && listMem[i].RRB_Queue_Matrix__r.Name == listMem[i+1].RRB_Queue_Matrix__r.Name){
system.debug('*****************entered if same proficiency');
tempSch.Next_User_Name__c = listMem[i+1].user__r.name;
tempSch.Next_User_Id__c = listMem[i+1].user__r.id;
}
else{
system.debug('*****************entered else next proficiency');
tempSch.Next_User_Name__c = firstmem.user__r.name;
tempSch.Next_User_Id__c = firstmem.user__r.id;
firstmem = listMem[i+1];

}

sched.add(tempSch);
}
//for last user
Scheduler__c tempSch =  new Scheduler__c();
tempSch.Name = listMem[memSize-1].user__r.name;
tempSch.Count__c = 0;
tempSch.Lead_Limit__c = listMem[memSize-1].user__r.Lead_limit__c;
tempSch.OOO__c = listMem[memSize-1].user__r.OOO__c;
tempSch.Last_Assigned__c = listMem[memSize-1].user__r.Last_assigned__c;
tempSch.Queue_Name__c = listMem[memSize-1].RRB_Queue_Matrix__c;
tempSch.Current_User_Name__c = listMem[memSize-1].user__r.name;
tempSch.Current_User_ID__c = listMem[memSize-1].user__r.id;
tempSch.User_Proficiency_Level__c = listMem[memSize-1].Queue_member_proficiency__c;
if(memSize>1 && listMem[memSize-1].Queue_member_proficiency__c == listMem[memSize-2].Queue_member_proficiency__c && listMem[memSize-1].RRB_Queue_Matrix__r.Name == listMem[memSize-2].RRB_Queue_Matrix__r.Name){
tempSch.Next_User_Name__c = firstmem.user__r.name;
tempSch.Next_User_Id__c = firstmem.user__r.id;
}
else{
tempSch.Next_User_Name__c = listMem[memSize-1].user__r.name;
tempSch.Next_User_Id__c = listMem[memSize-1].user__r.id;
}
sched.add(tempSch);
insert(sched);

}
}