jvimalprasathdev/src/objects/RRB_Queue_Matrix__c.object
<CustomObject>
    <fields>
        <fullName>Current_queue_proficiency_level__c</fullName>
        <label>Current queue proficiency level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Next_assigned_user__c</fullName>
        <label>Next assigned user</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>RRB Queue Matrix</label>
    <nameField>
        <label>Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Matrix</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/RRB_Queue_Member__c.object
<CustomObject>
    <fields>
        <fullName>RRB_Queue_Matrix__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RRB Queue Matrix</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>RRB Queue Members</relationshipLabel>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>RRB_Queue_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>RRB Queue Member</label>
    <nameField>
        <label>RRB Queue Members  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RRB Queue Members</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/Scheduler__c.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_Limit__c</fullName>
        <label>Lead Limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Queue Name</label>
        <referenceTo>RRB_Queue_Matrix__c</referenceTo>
        <relationshipLabel>Schedulers</relationshipLabel>
        <relationshipName>Schedulers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>User_Proficiency_Level__c</fullName>
        <description>To fetch value from Queue Members.</description>
        <label>Current User Proficiency Level</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Scheduler</label>
    <nameField>
        <label>Scheduler Object Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedulers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unlimited_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlimited Leads</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/ResetDailyCount.cls
public class ResetDailyCount {

public void reset(){

List<User> listUsers = [Select id,name,count__c,Lead_limit__c,Unlimited_Leads__c From User where id in (Select User__c From RRB_Queue_Member__c)];

for(user u : listUsers ){
u.count__c = 0;
if(u.Lead_limit__c == null)
 u.Lead_limit__c = 10;
if(u.Unlimited_Leads__c == true)
 u.Lead_limit__c = null;
 
}

List<RRB_Queue_Matrix__c> listQueueUpdate = new List<RRB_Queue_Matrix__c>();
List<RRB_Queue_Matrix__c> listQueue = [Select id,name,Next_assigned_user__c,Current_queue_proficiency_level__c FROM RRB_Queue_Matrix__c where id in (Select Queue_Name__c from Scheduler__c)];

for(RRB_Queue_Matrix__c Q : listQueue) {
system.debug('******QName'+Q.Name);
//if(Q.Next_assigned_user__c == '' ||Q.Next_assigned_user__c == null){
system.debug('******QName'+Q.Name);
List<Scheduler__c> scheduler = [Select id,name,User_Proficiency_Level__c,Queue_Name__r.Name FROM Scheduler__c Where Queue_Name__r.Name = :Q.name  order by id];
system.debug('******scheduler[0].name'+scheduler[0].name);
Q.Next_assigned_user__c = scheduler[0].name;
Q.Current_queue_proficiency_level__c = scheduler[0].User_Proficiency_Level__c;
system.debug('******Q.Next_assigned_user__c'+Q.Next_assigned_user__c);
system.debug('******Q.Current_queue_proficiency_level__c'+Q.Current_queue_proficiency_level__c);
listQueueUpdate.add(Q);
//}

}

update listUsers; 
update listQueueUpdate;
}
}