jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Avavilable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Avavilable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlimited_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlimited Leads</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/UserController2_Test.cls
@istest(seeAllData = true)
public class UserController2_Test{
	public static testmethod void UserController1_method(){
        ID currentuserID = userinfo.getUserId();
		ID CurrentpageId = ApexPages.currentPage().getParameters().get('id');
        User u = new User();
        u.Avavilable__c = true;
        u.OOO__c = false;
        u.Count__c = 10;
        u.Lead_limit__c = 100;
        u.Unlimited_Leads__c = false;
        UserController2 uc = new UserController2();
        uc.saveAction();
        uc.cancelAction();
    }
}