jvimalprasathdev/src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Avavilable__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Avavilable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lead_limit__c</fullName>
        <label>Lead limit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OOO__c</fullName>
        <defaultValue>false</defaultValue>
        <label>OOO</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Unlimited_Leads__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Unlimited Leads</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

jvimalprasathdev/src/classes/UserController2.cls
public with sharing class UserController2{
public List<User> filteredUsers{get;set;}

/* Updated for User Story B-433800 by Sunil  -- Start Here */
//public ID CurrentuserId;
//public ID CurrentpageId;

public ID CurrentuserId{get; set;}
public ID CurrentpageId{get; set;}


/* Updated for User Story B-433800 by Sunil  -- End Here */

public UserController2(){
CurrentpageId = ApexPages.currentPage().getParameters().get('id');
List<User> usrlist = new List<User>();
CurrentuserId = userinfo.getuserID();
filteredUsers = new List<User>();
string querystring;
querystring = 'Select Id, Name,ManagerId,Avavilable__c,OOO__c,Count__c,Lead_limit__c,Unlimited_Leads__c from User where id=:CurrentpageId and IsActive=True ';
filteredUsers = Database.query(querystring);

}
 public PageReference saveAction() {   
            try{
                update filteredUsers;
                }catch(exception e){
                }
                PageReference page = new Pagereference('/apex/QueueMgmt?Id='+CurrentuserId);
            page.setRedirect(true);
            return page;
 }
 
  public Pagereference cancelAction(){
        PageReference newpage = new Pagereference('/apex/QueueMgmt?Id='+CurrentuserId);
        newpage.setRedirect(true);
        return newpage;
 }

}